<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CompleteCountryDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // United States
            [
                'country_code' => 'US',
                'name' => 'United States',
                'image_url' => 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Washington, D.C.',
                'currency' => 'US Dollar (USD)',
                'language' => 'English',
                'description' => 'Home to world-renowned universities and diverse academic programs. The USA offers cutting-edge research facilities, innovative teaching methods, and unparalleled opportunities for international students.',
                'details' => 'The United States is the top destination for international students, hosting over 1 million students annually. With more than 4,000 accredited institutions, including Ivy League universities and top-ranked research centers, the USA provides an exceptional education system. Students benefit from Optional Practical Training (OPT) allowing 12 months of work experience, with STEM majors eligible for an additional 24-month extension.',
                'student_count' => 1075496,
                'tuition_range_min' => 25000,
                'tuition_range_max' => 55000,
                'living_cost_min' => 12000,
                'living_cost_max' => 25000,
                'visa_info' => 'F-1 Student Visa required. Application includes I-20 form, SEVIS fee ($350), visa interview, and proof of financial support. Processing time: 4-6 weeks. Students can work on-campus (20 hrs/week) and are eligible for CPT (internships) and OPT (post-graduation work).',
                'work_opportunities' => 'On-campus employment during studies (20 hrs/week). CPT for internships. OPT: 12 months (36 months for STEM). H-1B visa pathway available. Average starting salary: $60,000-$100,000.',
                'universities_count' => 150,
            ],
            // Canada
            [
                'country_code' => 'CA',
                'name' => 'Canada',
                'image_url' => 'https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Ottawa',
                'currency' => 'Canadian Dollar (CAD)',
                'language' => 'English, French',
                'description' => 'Welcoming, multicultural nation with high-quality education and clear pathways to permanent residence. Canada offers affordable tuition, safe environment, and the Post-Graduation Work Permit (PGWP) program.',
                'details' => 'Canada welcomes over 640,000 international students annually across 100+ universities and colleges. Known for its friendly immigration policies, students can work while studying and obtain a PGWP (up to 3 years) after graduation. Many students transition to permanent residence through Express Entry, Provincial Nominee Programs, or Canadian Experience Class.',
                'student_count' => 640000,
                'tuition_range_min' => 15000,
                'tuition_range_max' => 35000,
                'living_cost_min' => 12000,
                'living_cost_max' => 18000,
                'visa_info' => 'Study Permit required. Requires acceptance letter from DLI (Designated Learning Institution), proof of funds (CAD $10,000+), no criminal record, and medical exam. Biometrics required. Processing: 4-8 weeks. Spouse gets open work permit.',
                'work_opportunities' => 'Work 20 hrs/week during studies, full-time during breaks. PGWP: 8 months to 3 years based on program length. PR pathways through Express Entry (CEC), PNP. Average salary: CAD $50,000-$80,000.',
                'universities_count' => 30,
            ],
            // Australia
            [
                'country_code' => 'AU',
                'name' => 'Australia',
                'image_url' => 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Canberra',
                'currency' => 'Australian Dollar (AUD)',
                'language' => 'English',
                'description' => 'Innovative education system with beautiful campuses and vibrant cities. Australia offers the Group of Eight universities, stunning lifestyle, and the Temporary Graduate visa (subclass 485) for post-study work.',
                'details' => 'Australia hosts over 600,000 international students across 43 universities. The country is known for its high-quality education, research excellence, and relaxed lifestyle. The Group of Eight (Go8) are Australia\'s leading research universities. Students benefit from excellent weather, multicultural society, and strong employment outcomes with the 485 visa allowing 2-4 years of post-study work.',
                'student_count' => 624000,
                'tuition_range_min' => 20000,
                'tuition_range_max' => 45000,
                'living_cost_min' => 21000,
                'living_cost_max' => 30000,
                'visa_info' => 'Subclass 500 Student Visa required. Requires CoE (Confirmation of Enrolment), Genuine Temporary Entrant (GTE) statement, OSHC (health insurance), financial capacity proof. Processing: 4-6 weeks. Work allowed: 48 hrs/fortnight during study.',
                'work_opportunities' => 'Work 48 hrs/fortnight during studies, unlimited during breaks. Temporary Graduate visa (485): 2 years (Bachelor/Masters), 3 years (Masters by research), 4 years (PhD). Average salary: AUD $60,000-$85,000.',
                'universities_count' => 43,
            ],
            // Germany
            [
                'country_code' => 'DE',
                'name' => 'Germany',
                'image_url' => 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Berlin',
                'currency' => 'Euro (EUR)',
                'language' => 'German, English',
                'description' => 'World-class engineering and research with low or no tuition fees at public universities. Germany offers strong industry connections, the Job Seeker visa, and EU Blue Card opportunities.',
                'details' => 'Germany hosts over 400,000 international students across 400+ institutions. Public universities charge minimal or no tuition fees (€0-€3,000/year), making it one of the most affordable quality education destinations. Known for engineering, automotive, and technical excellence, Germany has strong industry ties. The 18-month Job Seeker visa and EU Blue Card provide excellent career opportunities.',
                'student_count' => 416437,
                'tuition_range_min' => 0,
                'tuition_range_max' => 3000,
                'living_cost_min' => 850,
                'living_cost_max' => 1200,
                'visa_info' => 'National Visa for studies required. Requires admission letter, blocked account (€11,208/year), health insurance, APS certificate (for most countries). Processing: 6-12 weeks. German language required for German-taught programs (TestDaF/DSH). Work allowed: 120 full days or 240 half days annually.',
                'work_opportunities' => 'Work 120 full days or 240 half days per year during studies. Job Seeker Visa: 18 months post-study to find employment. EU Blue Card with salary €56,800+. Settlement permit after 21-33 months. Average salary: €45,000-€70,000.',
                'universities_count' => 48,
            ],
            // France
            [
                'country_code' => 'FR',
                'name' => 'France',
                'image_url' => 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Paris',
                'currency' => 'Euro (EUR)',
                'language' => 'French, English',
                'description' => 'Rich cultural heritage with world-class universities and Grande Écoles. France offers affordable education, vibrant student life, and excellent opportunities in fashion, culinary arts, and business.',
                'details' => 'France welcomes over 370,000 international students to its universities, business schools, and specialized institutions. Public universities charge low tuition (€170-€650/year for EU, €2,770-€3,770/year for non-EU). The country is renowned for its Grande Écoles, offering elite education in engineering and business. Students enjoy rich cultural experiences, excellent public transportation, and student discounts throughout the country.',
                'student_count' => 370000,
                'tuition_range_min' => 2770,
                'tuition_range_max' => 15000,
                'living_cost_min' => 800,
                'living_cost_max' => 1500,
                'visa_info' => 'Long-stay student visa (VLS-TS) required. Requires Campus France validation, acceptance letter, financial proof (€615/month), health insurance, and accommodation proof. Processing: 3-4 weeks. Work allowed: 964 hours/year (approx. 20 hrs/week).',
                'work_opportunities' => 'Work up to 964 hours annually (part-time) during studies. Temporary residence permit (APS): 12 months post-study to find employment. Skills and Talents passport available. Average salary: €30,000-€45,000.',
                'universities_count' => 75,
            ],
            // Italy
            [
                'country_code' => 'IT',
                'name' => 'Italy',
                'image_url' => 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Rome',
                'currency' => 'Euro (EUR)',
                'language' => 'Italian, English',
                'description' => 'Historic universities dating back centuries, offering programs in arts, fashion, design, and engineering. Italy combines quality education with incredible culture, cuisine, and lifestyle.',
                'details' => 'Italy hosts over 100,000 international students across 97 universities, including the oldest university in the world (Bologna, founded 1088). Public universities offer affordable education (€900-€4,000/year). Italy is a top destination for arts, design, fashion, architecture, and culinary studies. Students enjoy UNESCO World Heritage sites, Mediterranean climate, and Italian lifestyle.',
                'student_count' => 100000,
                'tuition_range_min' => 900,
                'tuition_range_max' => 4000,
                'living_cost_min' => 700,
                'living_cost_max' => 1300,
                'visa_info' => 'Type D Student Visa required. Requires declaration of value (pre-enrollment), financial proof (€6,000-€7,000/year), health insurance, and accommodation. Processing: 4-6 weeks. Work allowed: 20 hrs/week during study, full-time during holidays.',
                'work_opportunities' => 'Work 20 hrs/week during studies, full-time during holidays. 12-month stay-back post-graduation for job search. Residence permit conversion possible. Average salary: €25,000-€40,000.',
                'universities_count' => 97,
            ],
            // Spain
            [
                'country_code' => 'ES',
                'name' => 'Spain',
                'image_url' => 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Madrid',
                'currency' => 'Euro (EUR)',
                'language' => 'Spanish, English',
                'description' => 'Dynamic education system with affordable tuition and vibrant culture. Spain offers excellent business schools, beautiful beaches, and a Mediterranean lifestyle perfect for international students.',
                'details' => 'Spain welcomes over 90,000 international students to its universities and business schools. Public universities are affordable (€750-€2,500/year), and the country offers numerous English-taught programs. Spain is ideal for business, tourism, Spanish language, and cultural studies. Students enjoy warm climate, world-famous cuisine, festivals, and easy travel throughout Europe.',
                'student_count' => 90000,
                'tuition_range_min' => 750,
                'tuition_range_max' => 12000,
                'living_cost_min' => 700,
                'living_cost_max' => 1200,
                'visa_info' => 'Student visa required for stays over 6 months. Requires acceptance letter, financial proof (€6,000-€7,200/year), health insurance, criminal record check. Processing: 3-4 weeks. Work allowed: Part-time with authorization, full-time during holidays.',
                'work_opportunities' => 'Part-time work during studies with special authorization. 1-year residence permit for job search after graduation. Skilled worker visa pathway. Average salary: €25,000-€38,000.',
                'universities_count' => 76,
            ],
            // Netherlands
            [
                'country_code' => 'NL',
                'name' => 'Netherlands',
                'image_url' => 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Amsterdam',
                'currency' => 'Euro (EUR)',
                'language' => 'Dutch, English',
                'description' => 'Progressive education system with over 2,100 English-taught programs. Netherlands offers innovative teaching, central European location, and the Orientation Year for job searching after graduation.',
                'details' => 'The Netherlands welcomes over 122,000 international students to 13 research universities and numerous universities of applied sciences. With 95% of Dutch people speaking English, international students feel at home. Known for innovative problem-based learning, the country offers excellent quality of life, bike-friendly cities, and easy travel across Europe. The Orientation Year visa allows 1 year to find employment.',
                'student_count' => 122000,
                'tuition_range_min' => 8000,
                'tuition_range_max' => 20000,
                'living_cost_min' => 800,
                'living_cost_max' => 1200,
                'visa_info' => 'MVV (entry visa) and residence permit required. University sponsors application through IND. Requires admission letter, financial proof (€11,500/year), health insurance. Processing: 4-6 weeks. Work allowed: 16 hrs/week during study, full-time with TWV during summer.',
                'work_opportunities' => 'Work 16 hrs/week during studies, full-time during summer (with work permit). Orientation Year: 1 year to find job after graduation. Highly Skilled Migrant Visa pathway. Average salary: €28,000-€50,000 starting.',
                'universities_count' => 13,
            ],
            // Sweden
            [
                'country_code' => 'SE',
                'name' => 'Sweden',
                'image_url' => 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Stockholm',
                'currency' => 'Swedish Krona (SEK)',
                'language' => 'Swedish, English',
                'description' => 'Innovative and progressive education system known for equality and sustainability. Sweden offers cutting-edge research, beautiful nature, and excellent work-life balance.',
                'details' => 'Sweden hosts over 30,000 international students across world-class universities. Known for innovation, equality, and sustainability, Swedish universities emphasize critical thinking and collaboration. The country offers stunning natural beauty, Northern Lights, and a high quality of life. Education is free for EU/EEA students; non-EU students pay tuition but benefit from scholarship opportunities.',
                'student_count' => 30000,
                'tuition_range_min' => 10000,
                'tuition_range_max' => 20000,
                'living_cost_min' => 900,
                'living_cost_max' => 1400,
                'visa_info' => 'Residence permit for studies required. Requires acceptance letter, financial proof (SEK 96,064/year), comprehensive health insurance. Processing: 2-4 months. Work allowed: Unlimited hours during studies with valid permit.',
                'work_opportunities' => 'Unlimited work hours during studies. 12-month extension post-graduation for job search. Work permit conversion after employment. Average salary: SEK 350,000-500,000 (€32,000-€46,000).',
                'universities_count' => 35,
            ],
            // Norway
            [
                'country_code' => 'NO',
                'name' => 'Norway',
                'image_url' => 'https://images.unsplash.com/photo-1513519107127-1bed33748e4c?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Oslo',
                'currency' => 'Norwegian Krone (NOK)',
                'language' => 'Norwegian, English',
                'description' => 'Free education at public universities with stunning fjords and natural beauty. Norway offers high living standards, progressive values, and excellent outdoor recreational opportunities.',
                'details' => 'Norway welcomes international students to its tuition-free public universities (only semester fees €60-100). Home to breathtaking fjords, Northern Lights, and midnight sun, Norway offers an exceptional student experience. The education system emphasizes independent thinking, creativity, and collaboration. Students benefit from high living standards, safety, and work opportunities.',
                'student_count' => 16000,
                'tuition_range_min' => 0,
                'tuition_range_max' => 1500,
                'living_cost_min' => 1000,
                'living_cost_max' => 1800,
                'visa_info' => 'Student residence permit required. Requires acceptance letter, financial proof (NOK 139,680/year), health insurance. Processing: 2-4 months. Work allowed: 20 hrs/week during semester, full-time during holidays.',
                'work_opportunities' => 'Work 20 hrs/week during studies, full-time during holidays. 1-year job-seeking permit after graduation. Work permit pathway available. Average salary: NOK 450,000-600,000 (€40,000-€53,000).',
                'universities_count' => 10,
            ],
            // Denmark
            [
                'country_code' => 'DK',
                'name' => 'Denmark',
                'image_url' => 'https://images.unsplash.com/photo-1513622790541-eaa84d356909?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Copenhagen',
                'currency' => 'Danish Krone (DKK)',
                'language' => 'Danish, English',
                'description' => 'World-renowned for happiness and quality of life. Denmark offers excellent education, hygge culture, and strong focus on innovation, design, and sustainability.',
                'details' => 'Denmark hosts over 35,000 international students at universities known for their informal teaching style and emphasis on group work. Education is free for EU/EEA students; non-EU students pay tuition but can apply for scholarships. Denmark consistently ranks as one of the happiest countries in the world, offering excellent quality of life, bike-friendly cities, and progressive social values.',
                'student_count' => 35000,
                'tuition_range_min' => 6000,
                'tuition_range_max' => 16000,
                'living_cost_min' => 900,
                'living_cost_max' => 1500,
                'visa_info' => 'Residence permit for studies required. Requires acceptance letter, financial proof (DKK 77,880/year), health insurance. Processing: 2-3 months. Work allowed: 20 hrs/week during semester, full-time during June-August and holidays.',
                'work_opportunities' => 'Work 20 hrs/week during studies, full-time during summer (June-August). 3-year establishment card after graduation for job search. Green Card scheme available. Average salary: DKK 350,000-450,000 (€47,000-€60,000).',
                'universities_count' => 8,
            ],
            // Finland
            [
                'country_code' => 'FI',
                'name' => 'Finland',
                'image_url' => 'https://images.unsplash.com/photo-1564882385-5bed6fa40769?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Helsinki',
                'currency' => 'Euro (EUR)',
                'language' => 'Finnish, Swedish, English',
                'description' => 'World-class education system consistently ranked #1 globally. Finland offers innovative teaching methods, stunning nature, Northern Lights, and safe, peaceful society.',
                'details' => 'Finland hosts over 20,000 international students at universities known for their high-quality education and innovative teaching. Free tuition for EU/EEA students; non-EU students pay fees but can apply for scholarships. Finland offers unique experiences like Northern Lights, midnight sun, and beautiful forests and lakes. The country excels in technology, design, and engineering education.',
                'student_count' => 20000,
                'tuition_range_min' => 4000,
                'tuition_range_max' => 18000,
                'living_cost_min' => 700,
                'living_cost_max' => 1200,
                'visa_info' => 'Residence permit for studies required. Requires acceptance letter, financial proof (€560/month), health insurance. Processing: 2-4 months. Work allowed: 30 hrs/week during semester, full-time during holidays.',
                'work_opportunities' => 'Work 30 hrs/week during studies, full-time during holidays. 1-year extended permit after graduation for job search. Continuous residence permit pathway. Average salary: €35,000-€50,000.',
                'universities_count' => 13,
            ],
            // Switzerland
            [
                'country_code' => 'CH',
                'name' => 'Switzerland',
                'image_url' => 'https://images.unsplash.com/photo-1527004013197-933c4bb611b3?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Bern',
                'currency' => 'Swiss Franc (CHF)',
                'language' => 'German, French, Italian, English',
                'description' => 'World-leading universities and research institutions nestled in the Alps. Switzerland offers multilingual environment, exceptional quality of life, and global business hub opportunities.',
                'details' => 'Switzerland hosts over 55,000 international students at prestigious institutions like ETH Zurich, EPFL, and University of Geneva. Known for excellence in hospitality, business, engineering, and sciences. Despite high living costs, public universities offer relatively affordable tuition (CHF 1,000-4,000/year). Students enjoy stunning Alpine scenery, world-class infrastructure, and central European location.',
                'student_count' => 55000,
                'tuition_range_min' => 1000,
                'tuition_range_max' => 4000,
                'living_cost_min' => 1500,
                'living_cost_max' => 2500,
                'visa_info' => 'Residence permit for studies required. Requires acceptance letter, financial proof (CHF 21,000/year), health insurance, accommodation proof. Processing: 8-12 weeks. Work allowed: 15 hrs/week during semester, full-time during holidays.',
                'work_opportunities' => 'Work 15 hrs/week during studies, full-time during holidays. 6-month extension after graduation for job search. Work permit after employment. Average salary: CHF 80,000-100,000 (€83,000-€104,000).',
                'universities_count' => 12,
            ],
            // New Zealand
            [
                'country_code' => 'NZ',
                'name' => 'New Zealand',
                'image_url' => 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Wellington',
                'currency' => 'New Zealand Dollar (NZD)',
                'language' => 'English, Māori',
                'description' => 'Stunning natural beauty combined with world-class education. New Zealand offers friendly culture, innovative programs, and post-study work visas up to 3 years for certain qualifications.',
                'details' => 'New Zealand hosts over 125,000 international students across 8 universities and numerous polytechnics. Known for its safe environment, outdoor lifestyle, and high-quality education, NZ provides an excellent student experience. The country offers practical, hands-on learning and strong support for international students. Post-study work visas allow graduates to work and gain experience in this beautiful country.',
                'student_count' => 125000,
                'tuition_range_min' => 22000,
                'tuition_range_max' => 32000,
                'living_cost_min' => 15000,
                'living_cost_max' => 20000,
                'visa_info' => 'Student Visa required. Requires offer of place, proof of funds (NZD $20,000/year), acceptable health and character, genuine student assessment. Processing: 4-6 weeks. Work allowed: 20 hrs/week during study, full-time during scheduled breaks.',
                'work_opportunities' => 'Work 20 hrs/week during semester, full-time during breaks. Post-study work visa: 1 year (Level 7 qualification), 2 years (Level 8), 3 years (Level 9/10). PR pathways available. Average salary: NZD $45,000-$65,000.',
                'universities_count' => 8,
            ],
            // Japan
            [
                'country_code' => 'JP',
                'name' => 'Japan',
                'image_url' => 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Tokyo',
                'currency' => 'Japanese Yen (JPY)',
                'language' => 'Japanese, English',
                'description' => 'Cutting-edge technology and ancient traditions blend perfectly. Japan offers world-class universities, safe environment, unique culture, and excellent career opportunities in tech and engineering.',
                'details' => 'Japan welcomes over 200,000 international students to its universities and specialized schools. Known for excellence in technology, engineering, robotics, and animation. Many programs available in English, especially at graduate level. Students experience unique Japanese culture, advanced technology, efficient public transport, and amazing food. The country offers scholarships through MEXT and universities.',
                'student_count' => 200000,
                'tuition_range_min' => 5000,
                'tuition_range_max' => 15000,
                'living_cost_min' => 800,
                'living_cost_max' => 1500,
                'visa_info' => 'Student visa (ryugaku) required. Requires Certificate of Eligibility (CoE), acceptance letter, financial proof (¥1,500,000/year), passport. Processing: 1-3 months. Work allowed: 28 hrs/week during semester, 40 hrs/week during holidays (with permission).',
                'work_opportunities' => 'Work up to 28 hrs/week during studies, 40 hrs/week during holidays. Designated Activities visa: up to 1 year job search after graduation. Skilled Professional visa pathway. Average salary: ¥3,500,000-¥5,000,000 (€26,000-€37,000).',
                'universities_count' => 86,
            ],
            // South Korea
            [
                'country_code' => 'KR',
                'name' => 'South Korea',
                'image_url' => 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Seoul',
                'currency' => 'South Korean Won (KRW)',
                'language' => 'Korean, English',
                'description' => 'Dynamic blend of tradition and ultra-modern technology. South Korea offers top universities, K-pop culture, advanced infrastructure, and growing opportunities in tech and business.',
                'details' => 'South Korea hosts over 150,000 international students at world-ranked universities. Known for excellence in technology, engineering, business, and Korean studies. Seoul is a vibrant megacity with cutting-edge technology, 24/7 lifestyle, and rich culture. Students benefit from affordable living costs, excellent public transport, fast internet, and Korean Wave (Hallyu) cultural experiences.',
                'student_count' => 150000,
                'tuition_range_min' => 4000,
                'tuition_range_max' => 12000,
                'living_cost_min' => 700,
                'living_cost_max' => 1200,
                'visa_info' => 'D-2 Student visa required. Requires acceptance letter, financial proof (USD $20,000/year), academic records, language proficiency. Processing: 2-4 weeks. Work allowed: 20 hrs/week during semester, full-time during holidays (with permission).',
                'work_opportunities' => 'Work 20 hrs/week during studies, full-time during holidays (with permission). D-10 job-seeking visa: 6-24 months after graduation. E-7 skilled work visa pathway. Average salary: KRW 35,000,000-50,000,000 (€26,000-€37,000).',
                'universities_count' => 42,
            ],
            // China
            [
                'country_code' => 'CN',
                'name' => 'China',
                'image_url' => 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Beijing',
                'currency' => 'Chinese Yuan (CNY)',
                'language' => 'Mandarin Chinese, English',
                'description' => 'Ancient civilization with modern economic powerhouse. China offers affordable education, numerous scholarships, rich culture, and opportunities in world\'s second-largest economy.',
                'details' => 'China hosts over 500,000 international students at rapidly improving universities. Many top universities now rank in global top 100. Chinese Government Scholarship and university scholarships available. Students experience 5,000 years of history, diverse landscapes, modern cities, and affordable living. Growing number of English-taught programs, especially at graduate level.',
                'student_count' => 500000,
                'tuition_range_min' => 3000,
                'tuition_range_max' => 10000,
                'living_cost_min' => 500,
                'living_cost_max' => 1000,
                'visa_info' => 'X1 (long-term) or X2 (short-term) student visa required. Requires admission letter (JW201/JW202), physical examination record, financial proof. Processing: 1-2 weeks. Work allowed: Part-time on-campus with approval.',
                'work_opportunities' => 'Limited part-time work on-campus. Internships possible with approval. Work permit (Z visa) after graduation requires employer sponsorship. Teaching English is popular option. Average salary: CNY 180,000-300,000 (€23,000-€38,000).',
                'universities_count' => 116,
            ],
            // India
            [
                'country_code' => 'IN',
                'name' => 'India',
                'image_url' => 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'New Delhi',
                'currency' => 'Indian Rupee (INR)',
                'language' => 'Hindi, English',
                'description' => 'Diverse, vibrant nation with affordable world-class education. India offers IITs, IIMs, ancient culture, spiritual heritage, and opportunities in fast-growing economy.',
                'details' => 'India welcomes over 50,000 international students to prestigious institutions like IITs (Indian Institutes of Technology) and IIMs (Indian Institutes of Management). English is widely used in education. Students experience incredible diversity, rich culture, spiritual traditions, and affordability. India is emerging as a global education hub with improving rankings and infrastructure.',
                'student_count' => 50000,
                'tuition_range_min' => 2000,
                'tuition_range_max' => 8000,
                'living_cost_min' => 300,
                'living_cost_max' => 700,
                'visa_info' => 'Student visa (Type X) required. Requires admission letter, financial proof, passport, medical certificate. Processing: 2-4 weeks. FRROs registration required upon arrival. Work allowed: Not permitted during studies, internships possible with approval.',
                'work_opportunities' => 'Part-time work not allowed during studies. Internships possible with FRRO approval. Employment visa (Type E) required for post-graduation work. OCI (Overseas Citizen of India) benefits for eligible students. Average salary: INR 400,000-800,000 (€4,500-€9,000).',
                'universities_count' => 45,
            ],
            // Singapore
            [
                'country_code' => 'SG',
                'name' => 'Singapore',
                'image_url' => 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Singapore',
                'currency' => 'Singapore Dollar (SGD)',
                'language' => 'English, Mandarin, Malay, Tamil',
                'description' => 'Global education hub with world-class universities. Singapore offers multicultural environment, safe city-state, excellent infrastructure, and gateway to Asia-Pacific opportunities.',
                'details' => 'Singapore hosts over 75,000 international students at NUS, NTU, and other top institutions. Consistently ranked among world\'s best universities for research and innovation. English is the language of instruction. Students enjoy one of the world\'s safest, cleanest, and most efficient cities. Strategic location offers easy travel across Asia. Strong job market and PR pathways available.',
                'student_count' => 75000,
                'tuition_range_min' => 20000,
                'tuition_range_max' => 40000,
                'living_cost_min' => 1000,
                'living_cost_max' => 2000,
                'visa_info' => 'Student\'s Pass required. Requires IPA (In-Principle Approval) letter, acceptance from institution, financial proof, medical examination. Processing: 2-4 weeks. Work allowed: 16 hrs/week during semester (with approval), full-time during holidays.',
                'work_opportunities' => 'Work up to 16 hrs/week during studies (with approval), full-time during holidays. 1-year Training Employment Pass (TEP) or Long-Term Visit Pass (LTVP) after graduation. PR application possible after employment. Average salary: SGD 42,000-60,000 (€29,000-€41,000).',
                'universities_count' => 6,
            ],
            // Brazil
            [
                'country_code' => 'BR',
                'name' => 'Brazil',
                'image_url' => 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Brasília',
                'currency' => 'Brazilian Real (BRL)',
                'language' => 'Portuguese',
                'description' => 'Largest economy in South America with vibrant culture and biodiversity. Brazil offers affordable education, beautiful beaches, carnival spirit, and emerging opportunities.',
                'details' => 'Brazil welcomes international students to public universities offering tuition-free education. Home to Amazon rainforest, beautiful beaches, and passionate culture. Students learn Portuguese while experiencing Carnival, samba, football culture, and Brazilian hospitality. Growing number of exchange programs and partnerships with international universities.',
                'student_count' => 18000,
                'tuition_range_min' => 0,
                'tuition_range_max' => 5000,
                'living_cost_min' => 400,
                'living_cost_max' => 900,
                'visa_info' => 'VITEM-IV (student) visa required. Requires acceptance letter, proof of financial means, criminal record check, health insurance. Processing: 4-6 weeks. Portuguese proficiency may be required. Work generally not allowed during studies.',
                'work_opportunities' => 'Limited work opportunities during studies. Internships possible with approval. Work visa requires employer sponsorship after graduation. Growing startup scene in São Paulo and Rio. Average salary: BRL 50,000-90,000 (€9,000-€16,000).',
                'universities_count' => 36,
            ],
            // South Africa
            [
                'country_code' => 'ZA',
                'name' => 'South Africa',
                'image_url' => 'https://images.unsplash.com/photo-1484318571209-661cf29a69c3?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Pretoria',
                'currency' => 'South African Rand (ZAR)',
                'language' => 'English, Afrikaans, Zulu',
                'description' => 'Rainbow nation with diverse culture and stunning landscapes. South Africa offers affordable English-taught programs, wildlife safaris, and gateway to African continent.',
                'details' => 'South Africa hosts over 85,000 international students at universities like University of Cape Town and Stellenbosch. All instruction in English at major universities. Students experience diverse cultures, stunning natural beauty from Table Mountain to Kruger National Park, and vibrant cities. Most affordable English-speaking destination for quality education.',
                'student_count' => 85000,
                'tuition_range_min' => 3000,
                'tuition_range_max' => 8000,
                'living_cost_min' => 500,
                'living_cost_max' => 1000,
                'visa_info' => 'Study visa required. Requires acceptance letter, medical and radiological reports, proof of financial means, police clearance. Processing: 8-12 weeks. Work allowed: Part-time with specific endorsement on study permit.',
                'work_opportunities' => 'Part-time work allowed with study visa endorsement. Limited hours during semester. Critical Skills Work Visa available for specific occupations post-graduation. PR pathways exist. Average salary: ZAR 250,000-400,000 (€13,000-€20,000).',
                'universities_count' => 26,
            ],
            // Russia
            [
                'country_code' => 'RU',
                'name' => 'Russia',
                'image_url' => 'https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Moscow',
                'currency' => 'Russian Ruble (RUB)',
                'language' => 'Russian',
                'description' => 'World\'s largest country with rich academic traditions. Russia offers affordable education, prestigious universities, unique culture, and opportunities in engineering and sciences.',
                'details' => 'Russia hosts over 300,000 international students at historic institutions like Lomonosov Moscow State University and St. Petersburg State University. Known for excellence in mathematics, physics, engineering, and medicine. Many programs available in English. Students experience rich cultural heritage, beautiful architecture, and diverse landscapes from Moscow\'s Red Square to Siberian wilderness.',
                'student_count' => 300000,
                'tuition_range_min' => 2000,
                'tuition_range_max' => 8000,
                'living_cost_min' => 300,
                'living_cost_max' => 700,
                'visa_info' => 'Student visa required. Requires official invitation from Russian institution, migration card, registration. Processing: 3-4 weeks. Russian language proficiency or preparatory year often required. Work limited during studies.',
                'work_opportunities' => 'Limited work opportunities during studies. Work permit required for employment. Teaching English or languages possible. Internships available with approval. Average salary: RUB 600,000-1,200,000 (€6,000-€12,000).',
                'universities_count' => 50,
            ],
            // Turkey
            [
                'country_code' => 'TR',
                'name' => 'Turkey',
                'image_url' => 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Ankara',
                'currency' => 'Turkish Lira (TRY)',
                'language' => 'Turkish, English',
                'description' => 'Bridge between Europe and Asia with ancient history. Turkey offers affordable education, rich cultural heritage, beautiful coastlines, and growing higher education sector.',
                'details' => 'Turkey welcomes over 180,000 international students to rapidly developing universities. Turkish Government Scholarship (Türkiye Bursları) covers all expenses. Students experience unique blend of Eastern and Western cultures, ancient sites like Cappadocia and Ephesus, and vibrant Istanbul. Growing number of English-taught programs, especially in engineering and business.',
                'student_count' => 180000,
                'tuition_range_min' => 400,
                'tuition_range_max' => 4000,
                'living_cost_min' => 300,
                'living_cost_max' => 700,
                'visa_info' => 'Student residence permit required. Requires acceptance letter, financial proof, health insurance, passport photos. Processing: 4-6 weeks. Apply online before arrival. Work allowed: 24 hrs/week with special permission after first year.',
                'work_opportunities' => 'Work up to 24 hrs/week after first year with permission. Graduates can apply for work permit with job offer. Growing job market in Istanbul and Ankara. Teaching English popular option. Average salary: TRY 180,000-300,000 (€5,000-€8,500).',
                'universities_count' => 58,
            ],
            // Ireland
            [
                'country_code' => 'IE',
                'name' => 'Ireland',
                'image_url' => 'https://images.unsplash.com/photo-1590004953392-5aba2e72269a?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Dublin',
                'currency' => 'Euro (EUR)',
                'language' => 'English, Irish',
                'description' => 'English-speaking EU member with growing tech hub. Ireland offers friendly culture, quality education, and the Third Level Graduate Scheme allowing 2 years of post-study work.',
                'details' => 'Ireland hosts over 35,000 international students across its universities and institutes of technology. As the European headquarters for major tech companies (Google, Facebook, Apple), Ireland offers excellent career opportunities. The education system is highly regarded, and as an EU member, graduates can work across Europe. The friendly Irish culture and beautiful landscapes make it an attractive destination.',
                'student_count' => 35000,
                'tuition_range_min' => 10000,
                'tuition_range_max' => 25000,
                'living_cost_min' => 10000,
                'living_cost_max' => 15000,
                'visa_info' => 'Study Visa required for non-EU students. Requires acceptance letter, financial proof (€10,000/year), private medical insurance, evidence of academic progression. Processing: 8-10 weeks. Work allowed: 20 hrs/week during term, 40 hrs/week during holidays.',
                'work_opportunities' => 'Work 20 hrs/week during term, full-time during holidays. Third Level Graduate Scheme: 2 years post-study work for degree holders. Critical Skills visa pathway. Tech industry opportunities. Average salary: €30,000-€50,000.',
                'universities_count' => 7,
            ],
        ];

        foreach ($countries as $countryData) {
            $country = Country::where('country_code', $countryData['country_code'])->first();
            if ($country) {
                $country->update($countryData);
                $this->command->info("✓ Updated {$countryData['name']} ({$countryData['country_code']}) with complete details");
            } else {
                $this->command->warn("✗ Country not found: {$countryData['name']} ({$countryData['country_code']})");
            }
        }

        $this->command->info("\n🎉 All countries have been updated with complete details matching UK format!");
    }
}
