<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountryDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [
                'name' => 'United States',
                'country_code' => 'USA',
                'image_url' => 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Washington, D.C.',
                'currency' => 'US Dollar (USD)',
                'language' => 'English',
                'description' => 'Home to world-renowned universities and diverse academic programs. The USA offers cutting-edge research facilities, innovative teaching methods, and unparalleled opportunities for international students.',
                'details' => 'The United States is the top destination for international students, hosting over 1 million students annually. With more than 4,000 accredited institutions, including Ivy League universities and top-ranked research centers, the USA provides an exceptional education system. Students benefit from Optional Practical Training (OPT) allowing 12 months of work experience, with STEM majors eligible for an additional 24-month extension.',
                'student_count' => 1075496,
                'tuition_range_min' => 25000,
                'tuition_range_max' => 55000,
                'living_cost_min' => 12000,
                'living_cost_max' => 25000,
                'visa_info' => 'F-1 Student Visa required. Application includes I-20 form, SEVIS fee ($350), visa interview, and proof of financial support. Processing time: 4-6 weeks. Students can work on-campus (20 hrs/week) and are eligible for CPT (internships) and OPT (post-graduation work).',
                'work_opportunities' => 'On-campus employment during studies (20 hrs/week). CPT for internships. OPT: 12 months (36 months for STEM). H-1B visa pathway available. Average starting salary: $60,000-$100,000.',
                'universities_count' => 150,
            ],
            [
                'name' => 'United Kingdom',
                'country_code' => 'UK',
                'image_url' => 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'London',
                'currency' => 'British Pound (GBP)',
                'language' => 'English',
                'description' => 'Rich academic tradition with prestigious universities like Oxford and Cambridge. The UK offers shorter degree durations, world-class research, and the new Graduate Route allowing 2-3 years of post-study work.',
                'details' => 'The UK hosts over 500,000 international students across 130+ universities. Known for academic excellence and shorter program durations (3-year bachelors, 1-year masters), the UK provides excellent value. The Graduate Route visa allows international students to work in the UK for 2 years (3 years for PhD graduates) after completing their degree.',
                'student_count' => 605130,
                'tuition_range_min' => 15000,
                'tuition_range_max' => 35000,
                'living_cost_min' => 12000,
                'living_cost_max' => 18000,
                'visa_info' => 'Tier 4 (General) Student Visa required. Requires CAS (Confirmation of Acceptance for Studies), financial proof, English language proficiency, and TB test. Healthcare surcharge: £470/year. Processing: 3 weeks. Work allowed: 20 hrs/week during term time.',
                'work_opportunities' => 'Part-time work (20 hrs/week) during studies, full-time during holidays. Graduate Route: 2 years work (3 years for PhD). Skilled Worker visa pathway available. Average salary: £25,000-£45,000.',
                'universities_count' => 90,
            ],
            [
                'name' => 'Canada',
                'country_code' => 'CAN',
                'image_url' => 'https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Ottawa',
                'currency' => 'Canadian Dollar (CAD)',
                'language' => 'English, French',
                'description' => 'Welcoming, multicultural nation with high-quality education and clear pathways to permanent residence. Canada offers affordable tuition, safe environment, and the Post-Graduation Work Permit (PGWP) program.',
                'details' => 'Canada welcomes over 640,000 international students annually across 100+ universities and colleges. Known for its friendly immigration policies, students can work while studying and obtain a PGWP (up to 3 years) after graduation. Many students transition to permanent residence through Express Entry, Provincial Nominee Programs, or Canadian Experience Class.',
                'student_count' => 640000,
                'tuition_range_min' => 15000,
                'tuition_range_max' => 35000,
                'living_cost_min' => 12000,
                'living_cost_max' => 18000,
                'visa_info' => 'Study Permit required. Requires acceptance letter from DLI (Designated Learning Institution), proof of funds (CAD $10,000+), no criminal record, and medical exam. Biometrics required. Processing: 4-8 weeks. Spouse gets open work permit.',
                'work_opportunities' => 'Work 20 hrs/week during studies, full-time during breaks. PGWP: 8 months to 3 years based on program length. PR pathways through Express Entry (CEC), PNP. Average salary: CAD $50,000-$80,000.',
                'universities_count' => 30,
            ],
            [
                'name' => 'Australia',
                'country_code' => 'AUS',
                'image_url' => 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Canberra',
                'currency' => 'Australian Dollar (AUD)',
                'language' => 'English',
                'description' => 'Innovative education system with beautiful campuses and vibrant cities. Australia offers the Group of Eight universities, stunning lifestyle, and the Temporary Graduate visa (subclass 485) for post-study work.',
                'details' => 'Australia hosts over 600,000 international students across 43 universities. The country is known for its high-quality education, research excellence, and relaxed lifestyle. The Group of Eight (Go8) are Australia\'s leading research universities. Students benefit from excellent weather, multicultural society, and strong employment outcomes with the 485 visa allowing 2-4 years of post-study work.',
                'student_count' => 624000,
                'tuition_range_min' => 20000,
                'tuition_range_max' => 45000,
                'living_cost_min' => 21000,
                'living_cost_max' => 30000,
                'visa_info' => 'Subclass 500 Student Visa required. Requires CoE (Confirmation of Enrolment), Genuine Temporary Entrant (GTE) statement, OSHC (health insurance), financial capacity proof. Processing: 4-6 weeks. Work allowed: 48 hrs/fortnight during study.',
                'work_opportunities' => 'Work 48 hrs/fortnight during studies, unlimited during breaks. Temporary Graduate visa (485): 2 years (Bachelor/Masters), 3 years (Masters by research), 4 years (PhD). Average salary: AUD $60,000-$85,000.',
                'universities_count' => 43,
            ],
            [
                'name' => 'Germany',
                'country_code' => 'DEU',
                'image_url' => 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Berlin',
                'currency' => 'Euro (EUR)',
                'language' => 'German, English (for many programs)',
                'description' => 'World-class engineering and research with low or no tuition fees at public universities. Germany offers strong industry connections, the Job Seeker visa, and EU Blue Card opportunities.',
                'details' => 'Germany hosts over 400,000 international students across 400+ institutions. Public universities charge minimal or no tuition fees (€0-€3,000/year), making it one of the most affordable quality education destinations. Known for engineering, automotive, and technical excellence, Germany has strong industry ties. The 18-month Job Seeker visa and EU Blue Card provide excellent career opportunities.',
                'student_count' => 416437,
                'tuition_range_min' => 0,
                'tuition_range_max' => 3000,
                'living_cost_min' => 850,
                'living_cost_max' => 1200,
                'visa_info' => 'National Visa for studies required. Requires admission letter, blocked account (€11,208/year), health insurance, APS certificate (for most countries). Processing: 6-12 weeks. German language required for German-taught programs (TestDaF/DSH). Work allowed: 120 full days or 240 half days annually.',
                'work_opportunities' => 'Work 120 full days or 240 half days per year during studies. Job Seeker Visa: 18 months post-study to find employment. EU Blue Card with salary €56,800+. Settlement permit after 21-33 months. Average salary: €45,000-€70,000.',
                'universities_count' => 48,
            ],
            [
                'name' => 'Netherlands',
                'country_code' => 'NLD',
                'image_url' => 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Amsterdam',
                'currency' => 'Euro (EUR)',
                'language' => 'Dutch, English',
                'description' => 'Progressive education system with over 2,100 English-taught programs. Netherlands offers innovative teaching, central European location, and the Orientation Year for job searching after graduation.',
                'details' => 'The Netherlands welcomes over 122,000 international students to 13 research universities and numerous universities of applied sciences. With 95% of Dutch people speaking English, international students feel at home. Known for innovative problem-based learning, the country offers excellent quality of life, bike-friendly cities, and easy travel across Europe. The Orientation Year visa allows 1 year to find employment.',
                'student_count' => 122000,
                'tuition_range_min' => 8000,
                'tuition_range_max' => 20000,
                'living_cost_min' => 800,
                'living_cost_max' => 1200,
                'visa_info' => 'MVV (entry visa) and residence permit required. University sponsors application through IND. Requires admission letter, financial proof (€11,500/year), health insurance. Processing: 4-6 weeks. Work allowed: 16 hrs/week during study, full-time with TWV during summer.',
                'work_opportunities' => 'Work 16 hrs/week during studies, full-time during summer (with work permit). Orientation Year: 1 year to find job after graduation. Highly Skilled Migrant Visa pathway. Average salary: €28,000-€50,000 starting.',
                'universities_count' => 13,
            ],
            [
                'name' => 'New Zealand',
                'country_code' => 'NZL',
                'image_url' => 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Wellington',
                'currency' => 'New Zealand Dollar (NZD)',
                'language' => 'English, Māori',
                'description' => 'Stunning natural beauty combined with world-class education. New Zealand offers friendly culture, innovative programs, and post-study work visas up to 3 years for certain qualifications.',
                'details' => 'New Zealand hosts over 125,000 international students across 8 universities and numerous polytechnics. Known for its safe environment, outdoor lifestyle, and high-quality education, NZ provides an excellent student experience. The country offers practical, hands-on learning and strong support for international students. Post-study work visas allow graduates to work and gain experience in this beautiful country.',
                'student_count' => 125000,
                'tuition_range_min' => 22000,
                'tuition_range_max' => 32000,
                'living_cost_min' => 15000,
                'living_cost_max' => 20000,
                'visa_info' => 'Student Visa required. Requires offer of place, proof of funds (NZD $20,000/year), acceptable health and character, genuine student assessment. Processing: 4-6 weeks. Work allowed: 20 hrs/week during study, full-time during scheduled breaks.',
                'work_opportunities' => 'Work 20 hrs/week during semester, full-time during breaks. Post-study work visa: 1 year (Level 7 qualification), 2 years (Level 8), 3 years (Level 9/10). PR pathways available. Average salary: NZD $45,000-$65,000.',
                'universities_count' => 8,
            ],
            [
                'name' => 'Ireland',
                'country_code' => 'IRL',
                'image_url' => 'https://images.unsplash.com/photo-1590004953392-5aba2e72269a?auto=format&fit=crop&w=1200&q=80',
                'capital' => 'Dublin',
                'currency' => 'Euro (EUR)',
                'language' => 'English, Irish',
                'description' => 'English-speaking EU member with growing tech hub. Ireland offers friendly culture, quality education, and the Third Level Graduate Scheme allowing 2 years of post-study work.',
                'details' => 'Ireland hosts over 35,000 international students across its universities and institutes of technology. As the European headquarters for major tech companies (Google, Facebook, Apple), Ireland offers excellent career opportunities. The education system is highly regarded, and as an EU member, graduates can work across Europe. The friendly Irish culture and beautiful landscapes make it an attractive destination.',
                'student_count' => 35000,
                'tuition_range_min' => 10000,
                'tuition_range_max' => 25000,
                'living_cost_min' => 10000,
                'living_cost_max' => 15000,
                'visa_info' => 'Study Visa required for non-EU students. Requires acceptance letter, financial proof (€10,000/year), private medical insurance, evidence of academic progression. Processing: 8-10 weeks. Work allowed: 20 hrs/week during term, 40 hrs/week during holidays.',
                'work_opportunities' => 'Work 20 hrs/week during term, full-time during holidays. Third Level Graduate Scheme: 2 years post-study work for degree holders. Critical Skills visa pathway. Tech industry opportunities. Average salary: €30,000-€50,000.',
                'universities_count' => 7,
            ],
        ];

        foreach ($countries as $countryData) {
            \App\Models\Country::updateOrCreate(
                ['country_code' => $countryData['country_code']],
                $countryData
            );
        }
    }
}
