<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $reviews = [
            [
                'name' => 'Sarah Mitchell',
                'email' => 'sarah.mitchell@email.com',
                'university' => 'Stanford University',
                'country' => 'USA',
                'program' => 'Computer Science',
                'rating' => 5,
                'content' => 'The guidance I received was exceptional! The team helped me every step of the way, from selecting the right university to securing my visa. I am now studying at Stanford and couldn\'t be happier with the support I received.',
                'year' => 2024,
                'scholarship' => 'Yes',
                'address' => '123 Main Street, New York, NY 10001, USA',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'James Chen',
                'email' => 'james.chen@email.com',
                'university' => 'University of Oxford',
                'country' => 'UK',
                'program' => 'Business Administration',
                'rating' => 5,
                'content' => 'Outstanding service! They made the entire application process seamless. I was accepted to Oxford with a partial scholarship, and the team even helped me prepare for my interviews. Highly recommend their services!',
                'year' => 2023,
                'scholarship' => 'Partial',
                'address' => '45 Oxford Road, London, OX1 2JD, United Kingdom',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'Maria Rodriguez',
                'email' => 'maria.rodriguez@email.com',
                'university' => 'University of Toronto',
                'country' => 'Canada',
                'program' => 'Engineering',
                'rating' => 5,
                'content' => 'I never thought studying abroad was possible for me, but this team made my dreams come true! They found scholarship opportunities I didn\'t know existed and guided me through every step. Now I\'m pursuing my engineering degree in Toronto!',
                'year' => 2024,
                'scholarship' => 'Yes',
                'address' => '789 King Street, Toronto, ON M5H 1A1, Canada',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'Ahmed Hassan',
                'email' => 'ahmed.hassan@email.com',
                'university' => 'University of Melbourne',
                'country' => 'Australia',
                'program' => 'Medicine',
                'rating' => 5,
                'content' => 'Exceptional guidance from start to finish. The team helped me navigate the complex application process for medical school in Australia. Their expertise in visa applications and scholarship hunting was invaluable. I secured a 50% scholarship!',
                'year' => 2023,
                'scholarship' => 'Partial',
                'address' => '234 Collins Street, Melbourne, VIC 3000, Australia',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'Emma Wilson',
                'email' => 'emma.wilson@email.com',
                'university' => 'MIT',
                'country' => 'USA',
                'program' => 'Data Science',
                'rating' => 5,
                'content' => 'Best decision ever! The personalized attention and expert advice I received made all the difference. They helped me craft a compelling application that got me into MIT. Forever grateful for their support throughout my journey!',
                'year' => 2024,
                'scholarship' => 'No',
                'address' => '567 Tech Avenue, Cambridge, MA 02139, USA',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'Raj Patel',
                'email' => 'raj.patel@email.com',
                'university' => 'University of Cambridge',
                'country' => 'UK',
                'program' => 'Economics',
                'rating' => 5,
                'content' => 'Professional, knowledgeable, and supportive! They guided me through selecting the perfect program and helped me secure admission to Cambridge. The team\'s expertise in UK universities is unmatched. Thank you for making my dream a reality!',
                'year' => 2023,
                'scholarship' => 'Partial',
                'address' => '12 Trinity Lane, Cambridge, CB2 1TN, United Kingdom',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'Sophie Laurent',
                'email' => 'sophie.laurent@email.com',
                'university' => 'McGill University',
                'country' => 'Canada',
                'program' => 'Psychology',
                'rating' => 4,
                'content' => 'Great service overall! They were very helpful in finding universities that matched my profile and budget. The application process was smooth, and I received excellent advice on writing my personal statement. Very satisfied with the outcome!',
                'year' => 2024,
                'scholarship' => 'No',
                'address' => '890 Sherbrooke Street, Montreal, QC H3A 0G4, Canada',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'Carlos Mendez',
                'email' => 'carlos.mendez@email.com',
                'university' => 'University of Sydney',
                'country' => 'Australia',
                'program' => 'Architecture',
                'rating' => 5,
                'content' => 'Incredible support throughout my entire journey! From choosing the right university to securing my student visa, the team was there every step of the way. I\'m now studying architecture at Sydney, and it\'s everything I dreamed of and more!',
                'year' => 2024,
                'scholarship' => 'Yes',
                'address' => '456 George Street, Sydney, NSW 2000, Australia',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'Yuki Tanaka',
                'email' => 'yuki.tanaka@email.com',
                'university' => 'Harvard University',
                'country' => 'USA',
                'program' => 'Law',
                'rating' => 5,
                'content' => 'Simply outstanding! The team\'s dedication and expertise helped me achieve what seemed impossible. They provided invaluable guidance on my application essays and interview preparation. I\'m now at Harvard Law School with a full scholarship!',
                'year' => 2023,
                'scholarship' => 'Yes',
                'address' => '321 Harvard Yard, Cambridge, MA 02138, USA',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'Lisa Anderson',
                'email' => 'lisa.anderson@email.com',
                'university' => 'London School of Economics',
                'country' => 'UK',
                'program' => 'Finance',
                'rating' => 5,
                'content' => 'Highly professional and efficient service! They helped me navigate the competitive admission process for LSE. Their insights into the UK education system and financial aid options were extremely helpful. I couldn\'t have done it without them!',
                'year' => 2024,
                'scholarship' => 'Partial',
                'address' => '67 Houghton Street, London, WC2A 2AE, United Kingdom',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'David Kim',
                'email' => 'david.kim@email.com',
                'university' => 'University of British Columbia',
                'country' => 'Canada',
                'program' => 'Environmental Science',
                'rating' => 4,
                'content' => 'Very helpful team! They provided excellent guidance on selecting programs that aligned with my career goals. The visa application process was made much easier with their support. Happy with my choice of UBC for environmental studies!',
                'year' => 2023,
                'scholarship' => 'No',
                'address' => '234 University Boulevard, Vancouver, BC V6T 1Z4, Canada',
                'consent' => true,
                'is_approved' => true,
            ],
            [
                'name' => 'Priya Sharma',
                'email' => 'priya.sharma@email.com',
                'university' => 'Queensland University',
                'country' => 'Australia',
                'program' => 'Marine Biology',
                'rating' => 5,
                'content' => 'Life-changing experience! The team not only helped me get admitted to my dream program but also connected me with other students who had gone through the same process. Their mentorship program is amazing. Now living my dream studying marine biology in Australia!',
                'year' => 2024,
                'scholarship' => 'Yes',
                'address' => '678 St Lucia Road, Brisbane, QLD 4072, Australia',
                'consent' => true,
                'is_approved' => true,
            ],
        ];

        foreach ($reviews as $review) {
            \App\Models\Review::create($review);
        }
    }
}
