<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ChatController extends Controller
{
    public function index()
    {
        return view('chat');
    }

    public function sendMessage(Request $request)
    {
        $request->validate([
            'message' => 'required|string|max:1000'
        ]);

        $message = trim($request->input('message'));

        // Generate bot response
        $response = $this->generateResponse($message);

        return response()->json(['response' => $response]);
    }

    private function generateResponse($message)
    {
        // Enhanced response logic for study abroad chatbot with comprehensive database
        $responses = [
            // Greetings
            'hello' => 'Hello! Welcome to StudyAbroad! 🎓 I\'m your AI assistant ready to help with universities, scholarships, visa processes, courses, and everything about studying abroad. What would you like to know?',
            'hi' => 'Hi there! 👋 I\'m here to provide detailed information about international education, from university selection to post-study work opportunities. How can I assist you today?',
            'hey' => 'Hey! Ready to explore study abroad opportunities? I have comprehensive information about countries, universities, scholarships, courses, and visa requirements. What interests you?',
            'good morning' => 'Good morning! ☀️ How can I assist you with your study abroad plans today? I can help with university details, scholarship applications, visa guidance, and more!',
            'good afternoon' => 'Good afternoon! 🌤️ I\'m here to help with your international education questions - universities, scholarships, courses, rankings, work opportunities, and visa processes.',
            'good evening' => 'Good evening! 🌙 How can I support your study abroad journey? Ask me about any aspect of international education!',

            // Help and general
            'help' => 'I can help you with: universities, courses, scholarships, visa requirements, application processes, cost information, and more. What specific topic interests you?',
            'what can you do' => 'I can provide information about universities, courses, scholarships, visa processes, admission requirements, living costs, and answer your study abroad questions.',
            'how can you help' => 'I can guide you through university selection, scholarship opportunities, visa applications, course recommendations, and answer questions about studying abroad.',

            // Universities - Comprehensive Details
            'university' => 'We partner with 500+ top universities worldwide! 🎓\n\nI can provide detailed information about:\n• University rankings and reputation\n• Programs and courses offered\n• Admission requirements and deadlines\n• Tuition fees and scholarships\n• Campus facilities and student life\n• Employment outcomes\n• Application process\n\nWhich specific university or country interests you?',
            'universities' => 'Our database includes prestigious universities from:\n🇺🇸 USA (Harvard, Stanford, MIT, Yale, Princeton)\n🇬🇧 UK (Oxford, Cambridge, Imperial College, UCL)\n🇨🇦 Canada (Toronto, UBC, McGill, Waterloo)\n🇦🇺 Australia (Melbourne, Sydney, ANU, UNSW)\n🇩🇪 Germany (TUM, LMU Munich, Heidelberg)\n🇳🇱 Netherlands (Delft, Amsterdam, Utrecht)\n🇸🇬 Singapore (NUS, NTU)\n🇯🇵 Japan (Tokyo, Kyoto)\n\nWould you like details about a specific country or field?',
            'best university' => 'The "best" university depends on your field, career goals, and preferences!\n\n🏆 Overall Rankings (QS 2025):\n1. MIT (USA) - Engineering, Technology\n2. Harvard (USA) - Business, Law, Medicine\n3. Stanford (USA) - Engineering, Business, CS\n4. Oxford (UK) - Humanities, Sciences\n5. Cambridge (UK) - Sciences, Engineering\n6. Toronto (Canada) - Research, Medicine\n7. Imperial College (UK) - Engineering, Medicine\n8. ETH Zurich (Switzerland) - Engineering, Sciences\n\n📚 Best by Field:\n• Business: Harvard, Stanford, INSEAD\n• Engineering: MIT, Stanford, Cambridge\n• Medicine: Harvard, Oxford, Johns Hopkins\n• Computer Science: MIT, Stanford, Carnegie Mellon\n• Arts: Yale, Oxford, UCLA\n\nWhat field are you interested in?',
            'ranking' => '🏆 University Rankings Overview:\n\n🌍 World Rankings (QS 2025):\n1. MIT (USA)\n2. Harvard (USA)\n3. Stanford (USA)\n4. Oxford (UK)\n5. Cambridge (UK)\n6. Toronto (Canada)\n7. Imperial College (UK)\n8. ETH Zurich (Switzerland)\n9. UCL (UK)\n10. Yale (USA)\n\n📊 Ranking Factors:\n• Academic reputation (40%)\n• Employer reputation (10%)\n• Faculty/Student ratio (20%)\n• Citations per faculty (20%)\n• International faculty/students (10%)\n\n🎯 Other Rankings:\n• Times Higher Education\n• Shanghai Rankings\n• US News Global Rankings\n• Subject-specific rankings\n\nWould you like rankings for a specific country or subject?',
            
            // Harvard University
            'harvard' => '🎓 Harvard University - USA\n\n🏆 Ranking: #2 World (QS 2025)\n📍 Location: Cambridge, Massachusetts\n📅 Founded: 1636 (Oldest in USA)\n\n💰 Costs:\n• Undergraduate: $54,000/year\n• Graduate: $50,000-70,000/year\n• Living: $20,000/year\n\n🎯 Popular Programs:\n• Business (HBS #1 globally)\n• Law (#1 globally)\n• Medicine\n• Engineering\n• Public Policy\n\n📋 Admission Requirements:\n• GPA: 3.9+ (average 4.18)\n• SAT: 1460-1580\n• TOEFL: 100+\n• Acceptance Rate: 3-4%\n\n💼 Career Outcomes:\n• Average Salary: $85,000+\n• Employment Rate: 95%\n• Top Recruiters: Google, McKinsey, Goldman Sachs\n\n🎓 Scholarships: Need-based (100% demonstrated need covered)\n\nWould you like application guidance?',
            'stanford' => '🎓 Stanford University - USA\n\n🏆 Ranking: #3 World (QS 2025)\n📍 Location: Stanford, California (Silicon Valley)\n📅 Founded: 1885\n\n💰 Costs:\n• Undergraduate: $56,000/year\n• Graduate: $54,000-68,000/year\n• Living: $20,000/year\n\n🎯 Top Programs:\n• Computer Science (#2 globally)\n• Engineering (#2 globally)\n• Business (MBA #2)\n• Medicine\n• Design\n\n📋 Admission:\n• GPA: 3.9+ (average 3.96)\n• SAT: 1470-1570\n• TOEFL: 100+\n• Acceptance: 3.7%\n\n💼 Career:\n• Average Salary: $95,000+\n• Startup Culture: Many alumni founders\n• Top Companies: Google, Apple, Tesla, Meta\n\n🎓 Scholarships: Need-blind admission, 100% need met\n\nInterested in applying?',
            'oxford' => '🎓 University of Oxford - UK\n\n🏆 Ranking: #4 World (QS 2025)\n📍 Location: Oxford, England\n📅 Founded: 1096 (World\'s oldest English-speaking university)\n\n💰 Costs:\n• Undergraduate: £25,000-35,000/year\n• Graduate: £28,000-50,000/year\n• Living: £12,000/year\n\n🎯 Famous Programs:\n• PPE (Philosophy, Politics, Economics)\n• Law (#4 globally)\n• Medicine (#2 globally)\n• Humanities (#1 globally)\n• Rhodes Scholars program\n\n📋 Admission:\n• A-Levels: A*A*A minimum\n• IELTS: 7.0+ (7.5 for some courses)\n• Interview required\n• Acceptance: 17% (varies by course)\n\n💼 Alumni:\n• 28 UK Prime Ministers\n• 30+ world leaders\n• 120+ Olympic medalists\n• Numerous Nobel laureates\n\n🎓 Scholarships: Rhodes, Clarendon, college scholarships\n\nWant to know more about programs?',
            'cambridge' => '🎓 University of Cambridge - UK\n\n🏆 Ranking: #5 World (QS 2025)\n📍 Location: Cambridge, England\n📅 Founded: 1209\n\n💰 Costs:\n• Undergraduate: £24,000-35,000/year\n• Graduate: £26,000-45,000/year\n• Living: £11,000/year\n\n🎯 Excellence In:\n• Natural Sciences (#3 globally)\n• Engineering (#6 globally)\n• Mathematics (#3 globally)\n• Computer Science (#5 globally)\n• Medicine (#3 globally)\n\n📋 Admission:\n• A-Levels: A*A*A minimum\n• IELTS: 7.0-7.5\n• Interview + written test\n• Acceptance: 21%\n\n💼 Notable:\n• 121 Nobel Prize winners\n• 15 British Prime Ministers\n• Stephen Hawking, Isaac Newton alumni\n\n🎓 Scholarships: Gates Cambridge, Trust scholarships\n\nInterested in specific programs?',
            'mit' => '🎓 Massachusetts Institute of Technology - USA\n\n🏆 Ranking: #1 World (QS 2025)\n📍 Location: Cambridge, Massachusetts\n📅 Founded: 1861\n\n💰 Costs:\n• Undergraduate: $55,000/year\n• Graduate: $53,000-60,000/year\n• Living: $19,000/year\n\n🎯 World Leader In:\n• Engineering (#1 globally)\n• Computer Science (#1 globally)\n• Physics (#1 globally)\n• Mathematics (#1 globally)\n• AI & Robotics (#1 globally)\n\n📋 Admission:\n• GPA: 3.9+ (average 4.17)\n• SAT: 1520-1580\n• TOEFL: 100+\n• Acceptance: 3.2%\n\n💼 Innovation:\n• 30,000+ active alumni companies\n• $1.9 trillion annual revenue\n• Top tech recruiters\n\n🎓 Scholarships: Need-based (100% need met)\n\nWant application tips?',
            'toronto' => '🎓 University of Toronto - Canada\n\n🏆 Ranking: #21 World (QS 2025), #1 Canada\n📍 Location: Toronto, Ontario\n📅 Founded: 1827\n\n💰 Costs:\n• Undergraduate: CAD $60,000/year\n• Graduate: CAD $25,000-50,000/year\n• Living: CAD $15,000/year\n\n🎯 Strong Programs:\n• Computer Science (AI pioneer)\n• Engineering\n• Medicine (#12 globally)\n• Business (Rotman)\n• Research (Top 10 globally)\n\n📋 Admission:\n• GPA: 85%+ (3.5+)\n• IELTS: 6.5+ (7.0 for some programs)\n• TOEFL: 100+\n• Acceptance: 43%\n\n💼 Career:\n• PGWP: 3-year work permit\n• PR pathway available\n• Top Canadian employers\n\n🎓 Scholarships: Lester B. Pearson, President\'s Scholars\n\nWant to know about programs?',

            // Countries - Detailed Information
            'usa' => '🇺🇸 Study in USA - Complete Guide\n\n💰 Costs:\n• Tuition: $25,000-55,000/year\n• Living: $12,000-25,000/year\n• Total: $40,000-80,000/year\n\n🎓 Top Universities:\n• MIT, Harvard, Stanford, Princeton, Yale\n• 150+ universities in Top 500\n• Flexible curriculum, research focus\n\n📚 Popular Programs:\n• STEM (OPT extension: 36 months)\n• Business (MBA, Marketing)\n• Engineering (CS, Mechanical, Electrical)\n• Medicine (requires USMLE)\n\n🛂 Visa Process:\n• F-1 Student Visa\n• I-20 document required\n• SEVIS fee: $350\n• Processing: 4-6 weeks\n\n💼 Work Opportunities:\n• On-campus: 20hrs/week during study\n• OPT: 12 months (36 for STEM)\n• CPT: Internships during study\n• Average salary: $60,000-100,000\n\n📋 Requirements:\n• GPA: 3.0+ (Bachelors), 3.5+ (Masters)\n• TOEFL: 80+ or IELTS: 6.5+\n• GRE/GMAT for graduate programs\n• SAT/ACT for undergraduate\n\n🎓 Scholarships: Merit-based, athletic, need-based\n• Fulbright Program\n• University scholarships\n\nInterested in specific universities?',
            'uk' => '🇬🇧 Study in UK - Complete Guide\n\n💰 Costs:\n• Tuition: £15,000-35,000/year\n• Living: £12,000-18,000/year\n• Total: £27,000-53,000/year\n\n🎓 Top Universities:\n• Oxford, Cambridge, Imperial, UCL, Edinburgh\n• 90+ universities in Top 500\n• Shorter programs (1 year Masters)\n\n📚 Popular Programs:\n• Business & Finance (London advantage)\n• Engineering (Imperial, Cambridge)\n• Law (Oxford, LSE)\n• Medicine (Oxford, Cambridge)\n• Arts & Humanities (Oxford, UCL)\n\n🛂 Visa Process:\n• Tier 4 (General) Student Visa\n• CAS from university required\n• Processing: 3 weeks\n• Healthcare Surcharge: £470/year\n\n💼 Post-Study Work:\n• Graduate Route: 2 years (3 for PhD)\n• Work 20hrs/week during term\n• Full-time during breaks\n• Average salary: £25,000-40,000\n\n📋 Requirements:\n• IELTS: 6.0-7.5 (varies by course)\n• Academic: 60-85% (varies by university)\n• Personal statement required\n• References needed\n\n🎓 Scholarships:\n• Chevening Scholarships (full)\n• Commonwealth Scholarships\n• University scholarships\n\nWant to know about specific cities?',
            'canada' => '🇨🇦 Study in Canada - Complete Guide\n\n💰 Costs:\n• Tuition: CAD $15,000-35,000/year\n• Living: CAD $12,000-18,000/year\n• Total: CAD $27,000-53,000/year\n\n🎓 Top Universities:\n• Toronto, UBC, McGill, Waterloo, McMaster\n• 30+ universities in Top 500\n• High quality, affordable education\n\n📚 Popular Programs:\n• Computer Science (AI hub)\n• Engineering (Co-op programs)\n• Business (Rotman, Schulich)\n• Healthcare (in-demand)\n• Hospitality & Tourism\n\n🛂 Visa Process:\n• Study Permit required\n• Acceptance letter needed\n• Proof of funds: CAD $10,000+\n• Processing: 4-8 weeks\n• Biometrics required\n\n💼 Work & Immigration:\n• Work 20hrs/week during study\n• Full-time during breaks\n• PGWP: 8 months to 3 years\n• PR pathways (Express Entry, PNP)\n• Average salary: CAD $50,000-70,000\n\n📋 Requirements:\n• IELTS: 6.0-6.5+ or TOEFL: 80-90+\n• GPA: 70-85%+ (varies)\n• Some programs need GRE/GMAT\n\n🎓 Scholarships:\n• Vanier Canada Graduate Scholarships\n• Ontario Graduate Scholarships\n• University-specific awards\n\n🏡 Benefits:\n• Safe, multicultural society\n• Healthcare access\n• Spouse work permit\n• PR opportunities\n\nInterested in specific provinces?',
            'australia' => '🇦🇺 Study in Australia - Complete Guide\n\n💰 Costs:\n• Tuition: AUD $20,000-45,000/year\n• Living: AUD $21,000/year (minimum)\n• Total: AUD $41,000-66,000/year\n\n🎓 Top Universities:\n• Melbourne, Sydney, ANU, UNSW, Queensland\n• 43 universities, all world-class\n• Group of Eight (Go8) - Elite universities\n\n📚 Popular Programs:\n• Engineering (Mining, Civil)\n• Business & Management\n• Health Sciences\n• IT & Computer Science\n• Hospitality & Tourism\n\n🛂 Visa Process:\n• Subclass 500 Student Visa\n• CoE required\n• OSHC (health insurance) mandatory\n• Processing: 4-6 weeks\n• Genuine Temporary Entrant (GTE) statement\n\n💼 Work Opportunities:\n• Work 48hrs/fortnight during study\n• Unlimited during breaks\n• Post-Study: 485 Visa (2-4 years)\n• Average salary: AUD $60,000-80,000\n\n📋 Requirements:\n• IELTS: 6.0-6.5+ or equivalent\n• Academic: 65-80%+ (varies)\n• Financial capacity proof\n\n🎓 Scholarships:\n• Australia Awards\n• Destination Australia\n• University-specific scholarships\n• Research Training Program\n\n🏖️ Lifestyle:\n• Excellent climate\n• Beach culture\n• Safe environment\n• Multicultural society\n\nWant info on specific cities?',
            'germany' => '🇩🇪 Study in Germany - Complete Guide\n\n💰 Costs:\n• Tuition: €0-3,000/year (PUBLIC)\n• Private: €20,000-30,000/year\n• Living: €850-1,200/month\n• Total: €10,000-15,000/year\n\n🎓 Top Universities:\n• TUM, LMU Munich, Heidelberg, RWTH Aachen\n• 48 universities in Top 500\n• Strong in Engineering & Sciences\n\n📚 Popular Programs:\n• Engineering (Automotive, Mechanical)\n• Computer Science\n• Business & Management\n• Medicine (in German)\n• Sciences\n\n🛂 Visa Process:\n• National Visa (Student)\n• Admission letter required\n• Blocked account: €11,208/year\n• Processing: 6-12 weeks\n• German embassy appointment\n\n💼 Work & Stay:\n• Work 120 full days or 240 half days/year\n• Job Seeker Visa: 18 months post-study\n• EU Blue Card eligibility\n• Average salary: €45,000-65,000\n\n📋 Requirements:\n• APS Certificate (for most countries)\n• IELTS/TOEFL for English programs\n• TestDaF/DSH for German programs\n• Academic: 70%+ (varies)\n\n🎓 Scholarships:\n• DAAD Scholarships (most popular)\n• Erasmus+\n• Deutschland stipendium\n\n🏰 Benefits:\n• Free/low tuition\n• Central Europe location\n• Strong job market\n• High living standards\n\nInterested in German language courses?',
            'netherlands' => '🇳🇱 Study in Netherlands - Complete Guide\n\n💰 Costs:\n• EU Students: €2,000-4,000/year\n• Non-EU: €8,000-20,000/year\n• Living: €800-1,200/month\n• Total: €15,000-30,000/year\n\n🎓 Top Universities:\n• Delft TU, Amsterdam, Utrecht, Leiden\n• 13 universities in Top 200\n• English-taught programs (2,100+)\n\n📚 Popular Programs:\n• Engineering (Delft #1)\n• Business & Economics\n• Social Sciences\n• Design & Architecture\n• Agriculture & Food Tech\n\n🛂 Visa Process:\n• MVV (provisional visa)\n• Residence Permit\n• University sponsors application\n• Processing: 4-6 weeks\n\n💼 Work Opportunities:\n• 16hrs/week during study\n• Full-time during summer\n• Orientation Year: 1 year job search\n• Highly Skilled Migrant Visa\n• Average salary: €28,000-45,000\n\n📋 Requirements:\n• IELTS: 6.0-6.5+ or TOEFL: 80+\n• Previous degree relevant\n• Motivation letter\n• Some need GRE/GMAT\n\n🎓 Scholarships:\n• Orange Knowledge Programme\n• Holland Scholarship\n• University scholarships\n• Erasmus Mundus\n\n🚲 Lifestyle:\n• Bike-friendly\n• English widely spoken\n• Central European location\n• Progressive society\n\nWant to know about specific cities?',

            // Scholarships - Enhanced with detailed information
            'scholarship' => 'Scholarships are a great way to fund your study abroad journey! We offer various types including merit-based, need-based, country-specific, and specialized awards. Scholarships can cover tuition, living expenses, or both. What type of scholarship are you interested in? I can provide detailed information on eligibility, application processes, and tips to increase your chances.',
            'scholarships' => 'Our comprehensive scholarship database includes:\n\n• Merit-based scholarships (for academic excellence)\n• Need-based scholarships (for financial need)\n• Full scholarships (100% coverage)\n• Partial scholarships (25-75% coverage)\n• Government scholarships (Chevening, DAAD, Erasmus+)\n• University scholarships\n• Sports scholarships\n• Research scholarships\n• Women and minority scholarships\n• Study abroad specific scholarships\n\nMany cover 25-100% of tuition costs. Would you like details on eligibility criteria, application processes, or specific scholarship types?',
            'merit scholarship' => 'Merit scholarships reward academic excellence and achievements. \n\nEligibility:\n• Minimum GPA: 3.0-4.0 (varies by program)\n• Strong standardized test scores (SAT/ACT for undergrad, GRE/GMAT for grad)\n• English proficiency (IELTS 6.5+ or TOEFL 80+)\n• Leadership roles and extracurricular activities\n\nApplication Process:\n1. Submit academic transcripts\n2. Provide test scores\n3. Write personal statement\n4. Get letters of recommendation\n\nTips: Maintain high GPA, excel in tests, and demonstrate leadership. Many universities offer automatic merit scholarships upon admission.',
            'need based scholarship' => 'Need-based scholarships help students with financial difficulties.\n\nEligibility:\n• Demonstrated financial need\n• Family income below certain thresholds\n• Academic merit (usually GPA 2.5+)\n• Enrollment in degree program\n\nRequired Documents:\n• Financial statements\n• Tax returns\n• Bank statements\n• Essays explaining financial situation\n\nApplication Process:\n1. Complete FAFSA or equivalent form\n2. Submit financial documents\n3. Write need-based essay\n4. Provide income verification\n\nTips: Be honest about your situation and explain how the scholarship will help your education goals.',
            'full scholarship' => 'Full scholarships cover 100% of tuition and often include living expenses, making education essentially free.\n\nTypes:\n• Government scholarships (Chevening, DAAD)\n• University presidential scholarships\n• International excellence awards\n• Research fellowships\n\nEligibility:\n• Exceptional academic record (GPA 3.8+)\n• Perfect test scores\n• Strong leadership and extracurriculars\n• Research experience (for grad students)\n\nCompetition Level: Very high - awarded to top 1-5% of applicants.\n\nTips: Apply to multiple programs, prepare outstanding application materials, and consider less competitive but still prestigious alternatives.',
            'partial scholarship' => 'Partial scholarships cover a portion of your education costs (25-75%), making them more accessible than full scholarships.\n\nCoverage:\n• Tuition only: $5,000-$20,000/year\n• Tuition + living: $10,000-$30,000/year\n• Renewable annually based on performance\n\nEligibility:\n• Good academic standing (GPA 3.0+)\n• Financial need (for some programs)\n• Field of study alignment\n\nStrategy: Combine multiple partial scholarships to cover significant costs. Many students receive 50-75% coverage through various awards.\n\nTips: Apply early, meet all deadlines, and don\'t limit yourself to one scholarship.',
            'scholarship application' => 'Applying for scholarships requires careful planning and organization.\n\nStep-by-Step Process:\n1. Research scholarships 2-3 months before deadlines\n2. Check eligibility requirements thoroughly\n3. Gather required documents early\n4. Prepare compelling essays and personal statements\n5. Secure strong letters of recommendation\n6. Submit applications before deadlines\n7. Follow up if needed\n\nRequired Documents:\n• Academic transcripts\n• Standardized test scores\n• Personal statement/essays\n• Letters of recommendation\n• Financial documents (for need-based)\n• Resume/CV\n\nTips: Start early, proofread everything, and keep copies of all submissions.',
            'scholarship deadline' => 'Scholarship deadlines vary widely and are crucial to track.\n\nCommon Deadlines:\n• Undergraduate: December-March for Fall intake\n• Graduate: October-January for Fall intake\n• Government scholarships: 6-12 months before study start\n• University scholarships: Vary by institution\n\nKey Points:\n• Early deadlines for competitive scholarships\n• Rolling admissions for some programs\n• Multiple rounds for some scholarships\n• International deadlines may differ\n\nTips: Create a scholarship calendar, set reminders, and apply to programs with different deadlines to maximize opportunities.',
            'scholarship requirements' => 'Scholarship requirements vary by type and sponsor, but common criteria include:\n\nAcademic Requirements:\n• Minimum GPA: 2.5-4.0 (varies by scholarship)\n• Standardized tests: SAT/ACT, GRE/GMAT, IELTS/TOEFL\n• Academic transcripts from previous institutions\n\nPersonal Requirements:\n• Personal statement or essays\n• Letters of recommendation (2-3)\n• Resume/CV highlighting achievements\n• Leadership and extracurricular activities\n\nAdditional Requirements:\n• Financial documents (for need-based)\n• Research proposals (for research scholarships)\n• Portfolio (for arts scholarships)\n• Citizenship/residency proof\n\nTips: Research each scholarship\'s specific requirements and prepare documents in advance.',
            'how to get scholarship' => 'Increasing your scholarship chances requires strategy and preparation.\n\nAcademic Excellence:\n• Maintain high GPA throughout studies\n• Excel in standardized tests\n• Take challenging courses\n\nStrong Application:\n• Write compelling personal statements\n• Secure excellent recommendations\n• Highlight leadership and achievements\n\nStrategic Approach:\n• Apply to multiple scholarships\n• Start applications early\n• Research thoroughly\n• Meet all deadlines\n• Follow up on applications\n\nAdditional Tips:\n• Network with scholarship recipients\n• Consider less competitive scholarships\n• Apply for local and international awards\n• Don\'t get discouraged by rejections\n\nSuccess Rate: Most students receive at least one scholarship with persistent effort.',
            'scholarship amount' => 'Scholarship amounts vary widely based on the sponsor and type.\n\nAmount Ranges:\n• Small awards: $500-$2,000/year\n• Medium awards: $2,000-$10,000/year\n• Large awards: $10,000-$25,000/year\n• Major awards: $25,000+/year\n• Full coverage: $30,000-$60,000+/year (includes living expenses)\n\nCoverage Types:\n• Tuition only\n• Tuition + living expenses\n• Tuition + books + supplies\n• Stipends for research/teaching\n\nFactors Affecting Amount:\n• Academic merit\n• Financial need\n• Field of study\n• University prestige\n• Country of origin\n\nStrategy: Combine multiple scholarships to maximize coverage.',
            'international scholarship' => 'International students have access to numerous scholarship opportunities.\n\nPopular Programs:\n• DAAD (Germany) - Full funding for German studies\n• Chevening (UK) - Leadership development scholarships\n• Commonwealth Scholarships - For Commonwealth countries\n• Erasmus+ (Europe) - EU-wide mobility program\n• Australia Awards - Full scholarships for Australian study\n• New Zealand Scholarships - Government-funded awards\n\nEligibility:\n• Citizenship of eligible countries\n• Academic excellence\n• Leadership potential\n• Commitment to development goals\n\nApplication Process:\n• Country-specific applications\n• Competitive selection process\n• Interviews and assessments\n\nTips: Check your country\'s eligibility and apply through official channels.',
            'government scholarship' => 'Government-funded scholarships offer comprehensive support for international students.\n\nMajor Programs:\n• Chevening Scholarships (UK) - For master\'s studies\n• DAAD Scholarships (Germany) - Research and study awards\n• Erasmus+ (European Union) - Mobility and cooperation\n• Australia Awards - Development-focused scholarships\n• Canadian Government Scholarships - Various programs\n• US Government Programs - Through State Department\n\nBenefits:\n• Full tuition coverage\n• Living expenses stipends\n• Health insurance\n• Travel costs\n• Academic and cultural support\n\nEligibility:\n• Academic merit\n• Leadership potential\n• Development impact\n• Language proficiency\n\nApplication: Highly competitive with early deadlines.',
            'university scholarship' => 'Most universities offer their own scholarship programs for international students.\n\nTypes:\n• Admission-based scholarships (automatic with offer)\n• Merit scholarships (separate application)\n• Departmental scholarships (field-specific)\n• Alumni scholarships (for alumni children)\n• Athletic scholarships (sports performance)\n• Research scholarships (graduate level)\n\nPopular University Scholarships:\n• Harvard University Scholarships\n• Stanford University Awards\n• University of Toronto Scholarships\n• University of Melbourne Awards\n• ETH Zurich Excellence Scholarships\n\nApplication Process:\n• Some automatic with admission\n• Others require separate application\n• Deadlines vary by university\n\nTips: Check university websites and apply early.',
            'sports scholarship' => 'Sports scholarships reward athletic talent and academic achievement.\n\nAvailable In:\n• USA (NCAA Division I universities)\n• Canada (CIS universities)\n• UK (BUCS system)\n• Australia (University sports programs)\n\nRequirements:\n• Athletic excellence in your sport\n• Academic qualifications (GPA 2.5+)\n• Team fit and recruitment potential\n• Sometimes tryouts or recruitment camps\n\nCoverage:\n• Full or partial tuition\n• Living expenses\n• Training and equipment costs\n• Academic support\n\nApplication Process:\n• Contact university athletic departments\n• Attend recruitment events\n• Submit athletic and academic credentials\n• May require video submissions\n\nTips: Start early, maintain academic eligibility, and consider walk-on opportunities.',
            'research scholarship' => 'Research scholarships support graduate students conducting research.\n\nTypes:\n• University research assistantships\n• Government research grants\n• Private foundation fellowships\n• Industry-sponsored research awards\n\nBenefits:\n• Tuition waivers\n• Monthly stipends ($1,000-$3,000)\n• Research funding\n• Conference travel support\n• Health insurance\n\nEligibility:\n• Admission to graduate program\n• Research proposal\n• Faculty supervisor support\n• Academic excellence\n\nFields: STEM, Social Sciences, Humanities\n\nApplication: Through graduate admissions or separate research applications.\n\nTips: Identify research interests early and build relationships with potential supervisors.',
            'women scholarship' => 'Women-specific scholarships promote gender equality in education.\n\nOrganizations:\n• AAUW International Fellowships\n• Zonta International\n• Women in STEM scholarships\n• Leadership and business scholarships\n• Country-specific women\'s programs\n\nFocus Areas:\n• STEM fields\n• Business and leadership\n• Social sciences\n• Arts and humanities\n• Developing country students\n\nBenefits:\n• Tuition coverage\n• Living expenses\n• Leadership development\n• Networking opportunities\n\nEligibility:\n• Female gender\n• Academic merit\n• Leadership potential\n• Commitment to women\'s advancement\n\nTips: Highlight leadership and community involvement in applications.',
            'minority scholarship' => 'Minority scholarships support underrepresented and disadvantaged groups.\n\nGroups Served:\n• Ethnic minorities\n• LGBTQ+ students\n• Students with disabilities\n• First-generation students\n• Refugees and displaced persons\n• Indigenous students\n\nOrganizations:\n• UNCF (United Negro College Fund)\n• Hispanic Scholarship Fund\n• Asian American scholarships\n• Native American programs\n• Disability-specific awards\n\nCoverage:\n• Tuition assistance\n• Living expenses\n• Academic support\n• Career development\n\nApplication: Demonstrate how your background and experiences align with scholarship goals.\n\nTips: Research culturally-specific scholarships and highlight unique perspectives.',
            'study abroad scholarship' => 'Study abroad scholarships specifically fund international education experiences.\n\nTypes:\n• Cultural exchange programs\n• Bilateral government agreements\n• University study abroad offices\n• Private foundation awards\n• Short-term exchange scholarships\n\nPrograms:\n• Erasmus+ (Europe)\n• Gilman Scholarship (USA)\n• DAAD (Germany)\n• Australia\'s New Colombo Plan\n• Canada\'s International Scholarships\n\nBenefits:\n• Program fees\n• Travel costs\n• Living expenses\n• Cultural immersion activities\n\nEligibility:\n• Enrollment in home institution\n• Academic standing\n• Language proficiency\n• Cultural interest\n\nTips: Check with your university\'s study abroad office for opportunities.',
            'financial aid' => 'Financial aid encompasses various funding sources beyond scholarships.\n\nOptions:\n• Scholarships and grants (need not repay)\n• Work-study programs (part-time jobs)\n• Student loans (must repay with interest)\n• Assistantships (teaching/research)\n• Emergency funds\n\nSources:\n• University financial aid offices\n• Government student aid programs\n• Private lenders\n• Nonprofit organizations\n\nApplication:\n• FAFSA or equivalent forms\n• Demonstrate financial need\n• Provide documentation\n\nTips: Compare aid packages, understand repayment terms, and explore all options before borrowing.',
            'funding' => 'Comprehensive funding strategies for international students.\n\nSources:\n• University scholarships (30-50% coverage)\n• Government grants and scholarships\n• Private foundation awards\n• Personal savings and family support\n• Part-time work opportunities\n• Student loans (as last resort)\n\nAverage Coverage: 30-70% of total costs through various sources.\n\nStrategy:\n1. Apply for multiple scholarships\n2. Seek university funding\n3. Consider work opportunities\n4. Plan budget carefully\n5. Look for emergency funds\n\nTips: Start planning 12-18 months before study start and track all funding sources.',

            // Visa
            'visa' => 'Visa requirements vary by country. Generally need: acceptance letter, financial proof, health insurance, and language proficiency. Processing time: 2-12 weeks. Which country interests you?',
            'visa requirements' => 'Common requirements: university acceptance, proof of funds ($10,000-30,000), health insurance, accommodation proof, and language tests (IELTS/TOEFL).',
            'student visa' => 'Student visas allow full-time study and part-time work. Most countries offer post-study work options. We provide detailed visa guidance for each destination.',

            // Applications
            'application' => 'Application process: research programs, check requirements, prepare documents, submit applications, and apply for visa. We provide step-by-step guidance.',
            'how to apply' => '1. Research universities and programs 2. Check admission requirements 3. Prepare documents (transcripts, LORs, SOP) 4. Take language tests 5. Submit applications 6. Apply for visa',
            'documents' => 'Required documents typically include: academic transcripts, language test scores, letters of recommendation, statement of purpose, CV, and financial statements.',

            // Costs
            'cost' => 'Costs vary by country and lifestyle. Include tuition, living expenses, insurance, and books. We provide detailed cost breakdowns. Which country are you considering?',
            'tuition' => 'Tuition fees: USA ($25k-55k), UK ($15k-30k), Canada ($12k-25k), Australia ($20k-35k), Germany ($0-500), Netherlands ($8k-15k) per year.',
            'living cost' => 'Monthly living costs: USA ($1,200-2,500), UK ($1,000-1,800), Canada ($800-1,500), Australia ($1,200-2,000), Germany ($800-1,200), Netherlands ($900-1,400).',

            // Degree Programs - Comprehensive Information
            'undergraduate' => '🎓 Undergraduate Programs (Bachelor\'s Degree)\n\n⏱️ Duration:\n• USA/Canada: 4 years\n• UK/Australia: 3 years\n• Germany/Netherlands: 3-4 years\n\n💰 Average Costs:\n• USA: $100,000-200,000 (total)\n• UK: £50,000-100,000 (total)\n• Canada: CAD $60,000-120,000 (total)\n• Australia: AUD $60,000-120,000 (total)\n• Germany: €10,000-40,000 (total)\n\n📚 Popular Fields:\n• Business Administration\n• Computer Science\n• Engineering (various streams)\n• Psychology\n• Biology/Life Sciences\n• Economics\n• Communications\n\n📋 Requirements:\n• High School Diploma (12 years)\n• GPA: 70-90%+ (varies)\n• SAT/ACT (for USA)\n• IELTS/TOEFL\n• Personal Statement\n• Extracurricular activities\n\n💼 Career Outcomes:\n• Entry-level positions\n• Average starting salary: $40,000-60,000\n• Further education opportunities\n\n🎓 Scholarships: Merit-based, sports, need-based\n\nWhich field interests you?',
            'masters' => '🎓 Master\'s Programs (Graduate Degree)\n\n⏱️ Duration:\n• USA/Canada: 1.5-2 years\n• UK: 1 year\n• Europe: 1-2 years\n• Australia: 1.5-2 years\n\n💰 Average Costs:\n• USA: $30,000-80,000 (total)\n• UK: £15,000-35,000 (total)\n• Canada: CAD $20,000-50,000 (total)\n• Europe: €5,000-30,000 (total)\n\n📚 Popular Programs:\n• MBA (Business)\n• MS Computer Science\n• MS Data Science\n• MS Engineering\n• MA Psychology\n• MPA/MIA (Public Policy)\n• MFA (Fine Arts)\n\n📋 Requirements:\n• Bachelor\'s degree\n• GPA: 3.0-3.5+\n• GRE/GMAT (often required)\n• IELTS/TOEFL\n• Work experience (for MBA)\n• Research experience (for research programs)\n• Statement of Purpose\n• Letters of Recommendation (2-3)\n\n💼 Career Advancement:\n• Mid-level to senior positions\n• Salary increase: 20-50%\n• Average salary: $60,000-100,000\n• Leadership roles\n\n🎓 Scholarships: Research assistantships, teaching assistantships, merit awards\n\nInterested in specific programs?',
            'mba' => '💼 MBA (Master of Business Administration)\n\n⏱️ Duration: 1-2 years (full-time), 2-3 years (part-time)\n\n💰 Top Programs Costs:\n• Harvard/Stanford: $150,000-180,000\n• Wharton/Kellogg: $140,000-160,000\n• INSEAD/LBS: £80,000-100,000\n• Canadian schools: CAD $80,000-120,000\n\n🏆 Top MBA Programs:\n1. Harvard Business School\n2. Stanford GSB\n3. Wharton (UPenn)\n4. MIT Sloan\n5. Chicago Booth\n6. INSEAD\n7. London Business School\n\n📋 Requirements:\n• Bachelor\'s degree\n• GMAT: 650-750+ (top schools)\n• Work experience: 3-7 years\n• IELTS/TOEFL\n• Essays and interviews\n• Leadership demonstrated\n\n📚 Specializations:\n• Finance & Investment Banking\n• Consulting & Strategy\n• Marketing & Brand Management\n• Entrepreneurship\n• Technology Management\n• Healthcare Management\n\n💼 Career Outcomes:\n• Average salary: $120,000-180,000\n• Top recruiters: McKinsey, BCG, Bain, Goldman Sachs\n• C-suite pathways\n• Startup founder opportunities\n\n🎓 Scholarships: Merit-based, diversity, industry-specific\n\nWant application tips?',
            'phd' => '🔬 PhD (Doctor of Philosophy)\n\n⏱️ Duration:\n• USA: 5-7 years\n• UK: 3-4 years\n• Europe: 3-5 years\n• Canada/Australia: 4-6 years\n\n💰 Funding:\n• Most PhD programs FULLY FUNDED\n• Stipend: $20,000-35,000/year\n• Tuition waiver included\n• Research grants available\n• Teaching assistantships\n\n📚 Popular Fields:\n• STEM (Physics, Chemistry, Biology)\n• Computer Science & AI\n• Engineering (all streams)\n• Social Sciences\n• Humanities\n• Business/Economics\n\n📋 Requirements:\n• Master\'s degree (preferred)\n• Strong research background\n• Publications (helpful)\n• GRE (for some programs)\n• Research proposal\n• IELTS/TOEFL\n• Strong recommendations from academics\n• Faculty supervisor confirmed\n\n💼 Career Paths:\n• Academic positions (Professor)\n• Research scientist (Industry)\n• R&D leadership roles\n• Policy advisor\n• Average salary: $80,000-150,000\n\n🎓 Scholarships:\n• Research assistantships (most common)\n• Fellowships (NSF, NIH)\n• Government scholarships\n\n🔬 Research Focus:\n• Original contribution to field\n• Publications required\n• Dissertation defense\n• Conference presentations\n\nInterested in specific research areas?',
            'courses' => '📚 Course & Program Categories\n\n🔵 STEM Fields:\n• Computer Science & IT\n• Engineering (20+ specializations)\n• Mathematics & Statistics\n• Physics & Astronomy\n• Chemistry & Materials Science\n• Biology & Life Sciences\n• Environmental Science\n\n🟢 Business & Economics:\n• Business Administration\n• Finance & Accounting\n• Marketing & Sales\n• Entrepreneurship\n• International Business\n• Economics\n• Supply Chain Management\n\n🟡 Arts & Humanities:\n• Psychology\n• English Literature\n• History\n• Philosophy\n• Languages\n• Communications\n• Fine Arts\n\n🟠 Health Sciences:\n• Medicine (MD/MBBS)\n• Nursing\n• Public Health\n• Pharmacy\n• Dentistry\n• Physical Therapy\n\n🔴 Social Sciences:\n• Sociology\n• Political Science\n• International Relations\n• Anthropology\n• Education\n\n🟣 Professional Programs:\n• Law (JD/LLM)\n• Architecture\n• Design\n• Hospitality\n\nWhat specific field interests you?',
            'programs' => '🎓 Available Program Levels\n\n1️⃣ UNDERGRADUATE (Bachelor\'s):\n• Duration: 3-4 years\n• Entry: High school diploma\n• Degrees: BA, BSc, BEng, BBA\n\n2️⃣ GRADUATE (Master\'s):\n• Duration: 1-2 years\n• Entry: Bachelor\'s degree\n• Degrees: MA, MSc, MEng, MBA\n\n3️⃣ DOCTORAL (PhD):\n• Duration: 3-7 years\n• Entry: Master\'s degree\n• Research-focused\n\n4️⃣ PROFESSIONAL:\n• MBA, Law (JD/LLM), Medicine (MD)\n• Specialized training\n• Industry certifications\n\n5️⃣ DIPLOMA & CERTIFICATES:\n• Duration: 6 months - 2 years\n• Vocational & technical\n• Career-focused\n\n6️⃣ ONLINE & HYBRID:\n• Flexible scheduling\n• Global access\n• Work while studying\n\n💡 Program Selection Factors:\n• Career goals\n• Budget\n• Duration\n• Location\n• Specialization\n• Post-study work options\n\nWhich level interests you?',
            'stem' => '🔬 STEM Programs (Science, Technology, Engineering, Mathematics)\n\n💻 Computer Science:\n• AI & Machine Learning\n• Cybersecurity\n• Software Engineering\n• Data Science\n• Top Schools: MIT, Stanford, CMU, Toronto\n• Average salary: $80,000-150,000\n\n⚙️ Engineering:\n• Mechanical, Electrical, Civil, Chemical\n• Aerospace, Biomedical, Environmental\n• Top Schools: MIT, Stanford, Berkeley, ETH Zurich\n• Average salary: $70,000-120,000\n\n🧮 Mathematics & Statistics:\n• Pure & Applied Mathematics\n• Statistics & Data Analytics\n• Actuarial Science\n• Top Schools: Cambridge, MIT, Princeton\n• Average salary: $70,000-110,000\n\n🧪 Physical Sciences:\n• Physics, Chemistry, Materials Science\n• Research-intensive\n• Top Schools: Cambridge, MIT, ETH Zurich\n• Average salary: $60,000-100,000\n\n🧬 Life Sciences:\n• Biology, Biotechnology, Biochemistry\n• Genetics, Neuroscience\n• Top Schools: Harvard, Stanford, Cambridge\n• Average salary: $65,000-110,000\n\n💡 Benefits:\n• High demand globally\n• OPT extension in USA (36 months)\n• Strong job prospects\n• Innovation opportunities\n• Higher salaries\n\n📋 Requirements:\n• Strong math/science background\n• Relevant undergraduate degree\n• GRE (for graduate programs)\n• Research experience (helpful)\n\nWhich STEM field interests you?',

            // Work Opportunities - Comprehensive Guide
            'work' => '💼 Work Opportunities for International Students\n\n📚 During Studies:\n• USA: On-campus 20hrs/week, CPT for internships\n• UK: 20hrs/week during term, full-time during breaks\n• Canada: 20hrs/week during term, unlimited during breaks\n• Australia: 48hrs/fortnight\n• Germany: 120 full days or 240 half days/year\n• Netherlands: 16hrs/week\n\n🎓 After Graduation:\n• USA: OPT (12 months), STEM OPT (36 months total)\n• UK: Graduate Route (2 years), 3 years for PhD\n• Canada: PGWP (8 months-3 years based on program)\n• Australia: 485 Visa (2-4 years based on degree)\n• Germany: Job Seeker Visa (18 months)\n• Netherlands: Orientation Year (1 year)\n\n💰 Average Salaries:\n• USA: $60,000-100,000\n• UK: £25,000-45,000\n• Canada: CAD $50,000-80,000\n• Australia: AUD $60,000-85,000\n• Germany: €45,000-70,000\n• Netherlands: €28,000-50,000\n\n🏢 Top Employers:\n• Tech: Google, Microsoft, Amazon, Apple\n• Finance: Goldman Sachs, JPMorgan, Citi\n• Consulting: McKinsey, BCG, Bain\n• Engineering: Boeing, Siemens, Tesla\n\n💡 Tips for Job Search:\n• Network early\n• Attend career fairs\n• Build relevant skills\n• Get internships\n• Use university career services\n\nWhich country interests you for work?',
            'job' => '💼 Post-Study Work Visas - Complete Breakdown\n\n🇺🇸 USA - OPT (Optional Practical Training):\n• Duration: 12 months (standard)\n• STEM extension: Additional 24 months (36 total)\n• Apply: 90 days before to 60 days after graduation\n• Cost: $410 application fee\n• Work: Full-time in field of study\n• H1B transition possible\n\n🇬🇧 UK - Graduate Route:\n• Duration: 2 years (Bachelor/Master), 3 years (PhD)\n• No sponsorship needed\n• Switch to Skilled Worker visa\n• Work: Any field, any employer\n• No minimum salary\n\n🇨🇦 Canada - PGWP (Post-Graduation Work Permit):\n• Duration: Matches program length (max 3 years)\n• Programs 8-24 months: Same duration PGWP\n• Programs 24+ months: 3-year PGWP\n• PR pathway: Canadian Experience Class\n• Spouse work permit available\n\n🇦🇺 Australia - 485 Visa:\n• Graduate Work: 18 months (Bachelor)\n• Post-Study Work: 2 years (Master), 3 years (PhD)\n• Regional: Additional 1-2 years\n• PR pathways available\n• Family can accompany\n\n🇩🇪 Germany - Job Seeker Visa:\n• Duration: 18 months to find job\n• Convert to work permit after job offer\n• EU Blue Card eligible (€56,800+ salary)\n• PR after 33 months (21 with B1 German)\n\n🇳🇱 Netherlands - Orientation Year:\n• Duration: 1 year\n• No sponsorship needed initially\n• Switch to Highly Skilled Migrant\n• Salary requirement: €30,000+\n\n💡 Maximizing Opportunities:\n• Start networking early\n• Gain relevant work experience\n• Build professional profiles (LinkedIn)\n• Attend industry events\n• Consider multiple countries\n\nNeed help with job search strategies?',
            'opt' => '🇺🇸 OPT - Optional Practical Training (USA)\n\n📋 Overview:\n• Allows 12 months work in USA after graduation\n• STEM majors: 24-month extension (36 total)\n• Must be related to field of study\n• Full-time or part-time allowed\n\n⏱️ Timeline:\n• Apply: 90 days before to 60 days after graduation\n• Processing: 3-5 months\n• Start work: After receiving EAD card\n• Grace period: 60 days after OPT expires\n\n💰 Costs:\n• Application fee: $410\n• STEM extension: $410 additional\n• Premium processing: Not available\n\n🔬 STEM OPT Extension:\n• 24 additional months (36 total)\n• Employer must use E-Verify\n• Formal training plan required\n• Fields: Science, Technology, Engineering, Math\n• Includes: CS, Engineering, Math, some Business programs\n\n📋 Requirements:\n• F-1 visa status\n• Completed degree (Associate, Bachelor, Master, PhD)\n• Work must be related to major\n• Employer anywhere in USA\n\n💼 After OPT:\n• Apply for H-1B visa (lottery system)\n• Consider other work visas\n• Or return to home country\n\n✅ Benefits:\n• Gain US work experience\n• Competitive salaries\n• Path to H-1B and Green Card\n• Build professional network\n\nNeed H-1B information?',
            'pgwp' => '🇨🇦 PGWP - Post-Graduation Work Permit (Canada)\n\n📋 Overview:\n• Work anywhere in Canada after graduation\n• Any field, any employer\n• Pathway to Permanent Residence\n• One-time opportunity\n\n⏱️ Duration Rules:\n• Program < 8 months: Not eligible\n• Program 8-24 months: PGWP matches program length\n• Program 24+ months: 3-year PGWP\n• Multiple programs: Can add durations (max 3 years)\n\n💰 Costs:\n• Application fee: CAD $255\n• Open work permit holder fee: CAD $100\n• Restoration fee: CAD $229 (if applicable)\n\n📋 Eligibility:\n• Study permit holder\n• Designated Learning Institution (DLI)\n• Full-time study (minimum 8 months)\n• Completed program\n• Apply within 180 days of completion\n\n💼 Work Conditions:\n• No restrictions on employer\n• No restrictions on job type\n• Can change jobs freely\n• Can work anywhere in Canada\n• Accumulate Canadian work experience\n\n🏠 PR Pathways:\n• Canadian Experience Class\n• Provincial Nominee Programs\n• Federal Skilled Worker\n• Atlantic Immigration Program\n• Rural and Northern Immigration Pilot\n\n👨‍👩‍👧 Family Benefits:\n• Spouse open work permit\n• Children can study (free in public schools)\n• Family can accompany\n\n✅ Advantages:\n• Flexible work options\n• Strong PR pathways\n• Family benefits\n• Quality of life\n\nInterested in PR process?',
            'h1b' => '🇺🇸 H-1B Visa - USA Work Visa\n\n📋 Overview:\n• Specialty occupation visa\n• Employer-sponsored\n• Initial: 3 years (extendable to 6)\n• Lottery system\n• Path to Green Card\n\n⏱️ Timeline:\n• Registration: March (annual)\n• Lottery: March-April\n• Application: If selected\n• Start date: October 1st\n• Processing: 2-4 months (or 15 days premium)\n\n💰 Costs:\n• Filing fee: $460\n• Fraud prevention: $500\n• ACWIA fee: $750-$1,500\n• Premium processing: $2,500 (15-day processing)\n• Total: ~$4,000-$5,000 (employer pays)\n\n📊 Statistics:\n• Annual cap: 85,000 (65k + 20k advanced degree)\n• Selection rate: ~25-30% (varies yearly)\n• Applications: 300,000-400,000 annually\n\n📋 Requirements:\n• Bachelor\'s degree or equivalent\n• Job offer from US employer\n• Specialty occupation (requires degree)\n• Prevailing wage compliance\n• LCA (Labor Condition Application)\n\n💼 Popular Industries:\n• Technology (60%+)\n• Finance\n• Healthcare\n• Engineering\n• Consulting\n\n🔄 From OPT to H-1B:\n• Work on OPT while waiting\n• Can reapply if not selected\n• Cap-gap extension if OPT expiring\n\n✅ Advantages:\n• Dual intent (can apply for Green Card)\n• Spouse (H-4) can work (with EAD)\n• Can change employers (portability)\n\n⚠️ Challenges:\n• Lottery uncertainty\n• Employer dependent\n• Annual cap limits\n\nNeed lottery tips?',
            'pr' => '🏠 Permanent Residence (PR) Pathways\n\n🇨🇦 Canada - Fastest PR:\n• Express Entry: 6-12 months\n• Provincial Nominee: 12-18 months\n• Canadian Experience Class (1 year work)\n• Points-based system (CRS)\n• Requirements:\n  - 1 year skilled work experience\n  - Language test (IELTS/CELPIP)\n  - Education assessment\n  - Age, adaptability factors\n\n🇦🇺 Australia:\n• Skilled Independent: 189 visa\n• State Sponsored: 190 visa\n• Points-based (min 65 points)\n• Duration: 12-24 months\n• Requirements:\n  - Skilled occupation\n  - Age under 45\n  - English proficiency\n  - Skills assessment\n\n🇺🇸 USA - Green Card:\n• Employment-based: 2-10 years\n• Family-based: 1-5 years\n• EB-1: Extraordinary ability (priority)\n• EB-2: Advanced degree + NIW\n• EB-3: Skilled worker\n• Long wait for some countries\n\n🇬🇧 UK - ILR:\n• Indefinite Leave to Remain\n• Duration: After 5 years on work visa\n• Requirements:\n  - 5 years continuous residence\n  - Life in the UK test\n  - English requirement\n  - No criminal record\n\n🇩🇪 Germany:\n• Settlement permit after 33 months\n• 21 months with B1 German\n• EU Blue Card holders faster\n• Requirements:\n  - German language (B1)\n  - Employment\n  - Pension contributions\n\n💡 Fastest PR:\n1. Canada: 1-2 years with PGWP\n2. Australia: 2-3 years\n3. Germany: 2-3 years\n4. UK: 5 years\n5. USA: 5-10+ years\n\nWant country-specific PR guidance?',

            // Language and tests
            'ielts' => 'IELTS required for UK, Canada, Australia, Netherlands. Minimum scores: 6.0-7.0. We recommend preparing 2-3 months. Practice tests and coaching available.',
            'toefl' => 'TOEFL required for USA universities. Minimum scores: 80-100. Computer-based test with reading, listening, speaking, and writing sections.',
            'gre' => 'GRE required for many graduate programs in USA. Tests verbal reasoning, quantitative reasoning, and analytical writing. Optional for some programs.',
            'gmat' => 'GMAT required for MBA programs. Tests analytical writing, integrated reasoning, quantitative, and verbal skills.',

            // Accommodation
            'accommodation' => 'Options include university dorms, private apartments, homestays, and shared housing. We help arrange pre-departure accommodation with airport pickup.',
            'housing' => 'Housing costs: $300-800/month for dorms, $500-1,500/month for apartments. We provide verified housing options and lease assistance.',

            // Health and insurance
            'health insurance' => 'Required for visa applications. Covers medical emergencies, doctor visits, and hospitalization. Costs $300-800/year depending on coverage.',
            'medical' => 'Health insurance mandatory for international students. Includes emergency care, routine checkups, and dental coverage in most plans.',

            // Farewell
            'bye' => 'Goodbye! Thank you for chatting with StudyAbroad. Feel free to return anytime for more information.',
            'thank you' => 'You\'re welcome! I\'m glad I could help with your study abroad questions. Don\'t hesitate to ask more.',
            'thanks' => 'You\'re welcome! Happy to assist with your international education journey.',
        ];

        $lowerMessage = strtolower($message);

        // Check for exact matches first
        if (isset($responses[$lowerMessage])) {
            return $responses[$lowerMessage];
        }

        // Check for partial matches (using word boundaries to avoid substring matches within words)
        foreach ($responses as $key => $response) {
            if (preg_match('/\b' . preg_quote($key, '/') . '\b/', $lowerMessage)) {
                return $response;
            }
        }

        // Default responses based on message content
        if (strpos($lowerMessage, 'how much') !== false || strpos($lowerMessage, 'cost') !== false) {
            return 'Costs vary by country and program. I can provide detailed cost breakdowns for specific destinations. Which country interests you?';
        }

        if (strpos($lowerMessage, 'where') !== false) {
            return 'We have partnerships with universities in over 100 countries. Popular destinations include USA, UK, Canada, Australia, Germany, and Netherlands. What type of program are you looking for?';
        }

        if (strpos($lowerMessage, 'when') !== false) {
            return 'Application deadlines vary by university and program. Most universities have multiple intakes: Fall (September), Spring (January), and Summer (May). We can help you with specific deadlines.';
        }

        if (strpos($lowerMessage, 'why') !== false) {
            return 'Study abroad offers world-class education, cultural experiences, career opportunities, and personal growth. Each country has unique advantages. What aspects interest you most?';
        }

        // Default response with comprehensive menu
        return "🎓 I'm your Study Abroad AI Assistant! I have comprehensive information on:\n\n📚 UNIVERSITIES:\n• Harvard, Stanford, MIT, Oxford, Cambridge, Toronto\n• University rankings and comparisons\n• Admission requirements\n• Campus life and facilities\n\n🌍 COUNTRIES:\n• USA, UK, Canada, Australia, Germany, Netherlands\n• Costs of living and tuition\n• Visa processes\n• Post-study work options\n\n💰 SCHOLARSHIPS:\n• Merit-based and need-based\n• Full and partial scholarships\n• Government scholarships (Chevening, DAAD, etc.)\n• University-specific awards\n• Application processes and tips\n\n📖 PROGRAMS & DEGREES:\n• Undergraduate (Bachelor's)\n• Masters (MS, MA, MBA)\n• PhD programs\n• STEM fields\n• Business, Engineering, Medicine\n\n💼 WORK OPPORTUNITIES:\n• Part-time work during studies\n• Post-study work visas (OPT, PGWP, PSW)\n• Salary expectations\n• PR pathways\n• H-1B visa information\n\n🛂 VISA PROCESSES:\n• Student visa requirements\n• Application procedures\n• Processing times\n• Costs and documentation\n\n🏆 RANKINGS:\n• QS World Rankings\n• Subject-specific rankings\n• Country comparisons\n\n💡 Type keywords like: 'Harvard', 'USA', 'MBA', 'scholarship', 'visa', 'OPT', 'PGWP', 'work', 'PR', etc.\n\nWhat would you like to know? Ask me anything! 😊";
    }
}
